### ISSUE TITLE
mapProjection in viewer props

### ISSUE THREAD

**Issue by tomgelu** [zouyaoji/vue-cesium#10]
Hi, is there anyway to add mapProjection to the viewer options? (all the options in https://cesiumjs.org/Cesium/Build/Documentation/Viewer.html are not described in your documentation, are they available anyway?)

**Comment by zouyaoji** [comment]
Hello, mapProjection is already a prop of viewer, but mapProjection generally uses default values, my documentation is not listed. use as follows:
```vue
<template>
    <cesium-viewer :mapProjection="mapProjection" @ready="viewerReady"></cesium-viewer>
</template>
<script>
    export default {
      data () {
        return {
          mapProjection: undefined
        }
      },
      methods: {
        viewerReady (cesiumInstance) {
           this.mapProjection = new GeographicProjection()
        }
      }
   }
</script>
```
