### ISSUE TITLE
请问可以展示打包好的3D模型吗？比如dae，gltf文件类型

### ISSUE THREAD

**Issue by Rhythmicc** [zouyaoji/vue-cesium#101]
如题；没在文档里找到相关方法。。（

**Comment by zouyaoji** [comment]
hi @Rhythmicc，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
