### ISSUE TITLE
能否直接获取点击位置的高程  目前工具中提供的获取高程感觉作用不大

### ISSUE THREAD

**Issue by anqimen** [zouyaoji/vue-cesium#107]
![image](https://user-images.githubusercontent.com/47019370/113694044-d8068700-9701-11eb-951a-3c21f941c5cc.png)

**Comment by zouyaoji** [comment]
hi @anqimen，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
2.0版本可以给vc-viewer绑定LEFT_CLICK事件，然后用Cesium API获取。
