### ISSUE TITLE
[Bug Report] VcViewer的cesiumReady事件没有触发，请教一下该怎么生效？

### ISSUE THREAD

**Issue by 651778286** [zouyaoji/vue-cesium#109]
### VueCesium version
3.0.1-beta.1

### OS/Browsers version
win10

### Vue version
3.0.9

### Reproduction Link
https://codepen.io/651778286/pen/RwpwZqQ?editors=1111

### Steps to reproduce
打开console控制台，没有找到onCesiumReady运行的痕迹

### What is Expected?
onCesiumReady方法中的代码被执行

### What is actually happening?
onCesiumReady方法中的代码未执行

**Comment by zouyaoji** [comment]
我看了，确实漏掉了，感谢反馈，下个版本可以正常使用。

**Comment by zouyaoji** [comment]
3.0.1-beta.6 修复
