### ISSUE TITLE
How to Use Cesium.IonWorldImageryStyle

### ISSUE THREAD

**Issue by mdasntc** [zouyaoji/vue-cesium#11]
I'd like to use the IonWorldImageryStyle. From what I've experienced terrain does not work without it as it gives an invalid access token response if using any other imagery provider:

`XHRGEThttps://api.cesium.com/v1/assets/1/endpoint?access_token=xxxxxxxxxxxxxx
[HTTP/2.0 401 Unauthorized 99ms]

JSON
code InvalidCredentials
message Invalid access token
Response payload 1
{"code":"InvalidCredentials","message":"Invalid access token"}`

Below is the image provider I'm using in a jQuery project using Cesium:

` imageryProvider: Cesium.createWorldImagery({
    style: Cesium.IonWorldImageryStyle.AERIAL_WITH_LABELS
}),`

**Comment by zouyaoji** [comment]
Are you using the default token?
Try applying for your own token at [https://cesium.com/ion](https://cesium.com/ion)
