### ISSUE TITLE
集成vue-cesium和arcgis api for js 4.x，同时加载导致vue-cesium报错

### ISSUE THREAD

**Issue by flyxiaokang** [zouyaoji/vue-cesium#111]

**Comment by zouyaoji** [comment]
hi @flyxiaokang，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
