### ISSUE TITLE
[Bug Report] 设置maximumZoomDistance和minimumZoomDistance后，并没有对导航控件生效

### ISSUE THREAD

**Issue by 651778286** [zouyaoji/vue-cesium#114]
### VueCesium version
3.0.1-beta.7

### OS/Browsers version
win10 / chrome91.0.4472.106（正式版本） （64 位）

### Vue version
3.1.1

### Reproduction Link
https://codepen.io/651778286/pen/vYxbYQm

### Steps to reproduce
连续点击导航控件的放到或者缩小按钮

### What is Expected?
onViewerReady方法中的代码生效，
即摄像机的距离被限制在10000000~50000000m范围内

### What is actually happening?
摄像机的距离并没有被限制住

**Comment by zouyaoji** [comment]
https://github.com/zouyaoji/vue-cesium/blob/dev/packages/controls/zoom-control/use-zoom-control.ts#L97

缩放控件用到的api是 viewer.camera.flyTo .

可能是 Cesium 这个 api 就没有根据 screenSpaceCameraController.maximumZoomDistance 来限制。

我先看看官方有没有什么说明或者解决方案。

**Comment by zouyaoji** [comment]
等官方解决。

https://github.com/CesiumGS/cesium/issues/9620#issuecomment-867256142

**Comment by IKangXu** [comment]
更换FlyTo到flyToBoundingSphere应该可以解决问题。
