### ISSUE TITLE
[Bug Report] vc-navigation罗盘GPS定位功能不完善：3D切换到2D视图后罗盘坐标系没有更新为EPSG:4326

### ISSUE THREAD

**Issue by liuqun** [zouyaoji/vue-cesium#118]
### VueCesium version
2.2.5

### OS/Browsers version
Windows10/Chrome最新版

### Vue version
3.1.4

### Steps to reproduce
- vue版本：2.6.12
- vue-cesium-v2版本：2.2.5

设置sceneModePicker=true开启3D/2D视图切换

```
            <vc-viewer
                ref="vcViewer"
                :sceneMode="sceneMode"
                :sceneModePicker="sceneModePicker"
                @ready="ready"
            >
```
...
```
data() {
    return {
        sceneMode: 3,
        sceneModePicker: true,
}
```

### What is Expected?
从3D切换到2D视图后罗盘坐标系同步更新为EPSG:4326，2D视图能够进行GPS定位

### What is actually happening?
vc-navigation罗盘GPS定位功能不完善：3D切换到2D视图后罗盘坐标系没有更新为EPSG:4326。
GPS定位到错误的2D位置

**Comment by zouyaoji** [comment]
重现了。
请 @ayiyayiyo 看一下
