### ISSUE TITLE
vue-cesium2.x

### ISSUE THREAD

**Issue by Japheth1989** [zouyaoji/vue-cesium#122]
vue-cesium2.x还会维护更新吗？我看到2.x的好多组件功能不完善。

**Comment by zouyaoji** [comment]
hi @Japheth1989，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
