### ISSUE TITLE
[Feature Request] vue-cesium2.x还维护吗

### ISSUE THREAD

**Issue by Japheth1989** [zouyaoji/vue-cesium#123]
### Existing Component
是

### Component Name
vc-navigation

### Description
vue-cesium2.x还会维护更新吗？我看2.x的组件相比3.x功能不完善。

**Comment by zouyaoji** [comment]
你好，目前vue2版本只修改bug了。请优先选择vue3版本的。

**Comment by Japheth1989** [comment]
> 你好，目前vue2版本只修改bug了。请优先选择vue3版本的。

目前项目采用的是vue2.0，vue_cli3脚手架，引用不了vue3.0版本的组件，请问还有别的办法吗？

**Comment by zouyaoji** [comment]
@Japheth1989 没办法哈，只有升级项目的vue版本到vue3才行。

**Comment by Japheth1989** [comment]
> @Japheth1989 没办法哈，只有升级项目的vue版本到vue3才行。

了解！谢谢。
