### ISSUE TITLE
量算工具自定义isActive失效

### ISSUE THREAD

**Issue by Cassieqian** [zouyaoji/vue-cesium#127]
量算工具，自定义 -------drawingActionInstance.isActive ? 'success' : 'primary'" 这一句失效了

**Comment by zouyaoji** [comment]
hi @Cassieqian，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
