### ISSUE TITLE
[Bug Report] 量算工具 自定义 isActive失效

### ISSUE THREAD

**Issue by Cassieqian** [zouyaoji/vue-cesium#128]
### VueCesium version
3.0.2-beta.6

### OS/Browsers version
windows10 64位/ chrome最新版

### Vue version
3.2.21

### Cesium version
1.87.0

### Reproduction Link
https://codepen.io/zouyaoji/null

### Steps to reproduce
量算工具，自定义量算工具，"drawingActionInstance.isActive ? 'success' : 'primary'"这一句失效

### What is Expected?
点工具，对应按钮高亮

### What is actually happening?
isActive不生效

**Comment by zouyaoji** [comment]
已重现，查原因中……

**Comment by zouyaoji** [comment]
@Cassieqian 最新版试试咧

**Comment by Cassieqian** [comment]
已解决，感谢
