### ISSUE TITLE
为什么感觉vue版本的地图上面不清晰呢

### ISSUE THREAD

**Issue by joinDonk** [zouyaoji/vue-cesium#135]

**Comment by zouyaoji** [comment]
hi @joinDonk，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
