### ISSUE TITLE
部署后地球不显示，只有星空，已经设了accessToken了

### ISSUE THREAD

**Issue by NSinC-LJ** [zouyaoji/vue-cesium#136]

**Comment by zouyaoji** [comment]
hi @NSinC-LJ，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
