### ISSUE TITLE
[Bug Report] jsdelivr cdn失效了

### ISSUE THREAD

**Issue by 651778286** [zouyaoji/vue-cesium#139]
### VueCesium version
3.0.3

### OS/Browsers version
window 10

### Vue version
3.2.26

### Cesium version
1.88.0

### Reproduction Link
https://codepen.io/651778286/pen/KKXqRxw

### Steps to reproduce
不FQ打开网址，发现加载页面失败
查看开发者工具，发现jsdelivr cdn相关的cesium文件加载失败
直接通过浏览器打开对应的连接，提示“您的连接不是私密连接”

### What is Expected?
不FQ，cesium相关的文件能够正常访问，页面正常加载

### What is actually happening?
不FQ，cesium相关的文件无法正常访问，页面无法正常加载

**Comment by zouyaoji** [comment]
我这未重现呢，是不是你网络原因？如果确实不行，你试试//unpkg.com/vue-cesium@next的吧

![image](https://user-images.githubusercontent.com/24430116/146727623-cb93bb9a-e593-4520-a8ba-166e405ff038.png)

**Comment by zouyaoji** [comment]
@651778286 应该是这个cdn挂了 群里也有人说了，用cdn的话换一个吧。

**Comment by 651778286** [comment]
墙内使用墙外资源还是风险太大了，昨天就被坑了，一个重要项目掉了链子🤣🤣🤣

**Comment by 651778286** [comment]
还是很感谢您的工作👍👍👍

**Comment by zouyaoji** [comment]
@651778286 可以搞个机制，判断cdn挂了的时候就引项目里面的cesium
