### ISSUE TITLE
什么时候可以出说明文档阿

### ISSUE THREAD

**Issue by cehui0303** [zouyaoji/vue-cesium#14]
没有说明文档很难操作。如何在其它组件里面获取cesuim对象

**Comment by zouyaoji** [comment]
我自己一般是存vuex。不过存之前要冻结一下对象，Object.freeze()，不然会影响性能。具体可以参考vue官方文档哈。等后面我另外弄个引入vuex的例子吧。

**Comment by zouyaoji** [comment]
在线问答参考 [中文](https://zouyaoji.top/vue-cesium/#/zh/index)。
