### ISSUE TITLE
[Bug Report] Vue Cesium not compiling in Quasar 3 app

### ISSUE THREAD

**Issue by ldtsch** [zouyaoji/vue-cesium#144]
### VueCesium version
3.0.5

### OS/Browsers version
WSL2 (Ubuntu)

### Vue version
3.2.26

### Cesium version
1.88.0

### Reproduction Link
https://github.com/ldtsch/quasar-vue-cesium

### Steps to reproduce
run `quasar dev` or `quasar build` in top folder.
Compilation won't work because of lodash submodule import error. See full error message in README.md in repository.

The application is a barebone quasar application created by `quasar create`. Then, vue-cesium has been added via `yarn add vue-cesium@3.0.5`. Afterwards, the boot file (`boot/vue-cesium.js`) has been created, and added to `quasar.conf`.

### What is Expected?
Application runs

### What is actually happening?
Compilation fails

**Comment by zouyaoji** [comment]
@ldtsch 
Thanks for the feedback, the bug has been reproduced and is being fixed. . . If you are in a hurry, you can consider the [quasar-vite plugin](https://quasar.dev/start/vite-plugin#introduction), which I tested is available.
