### ISSUE TITLE
onready 事件里面为什么不能给camera设置事件

### ISSUE THREAD

**Issue by cehui0303** [zouyaoji/vue-cesium#15]
参考你的文档，在onready事件里面给camera添加事件，结果提示camera.changed为undefine
// 在这儿获取Cesium和viewer实例，再执行相关逻辑代码
					this.camera.position.longitude = 116.46;
					this.camera.position.latitude = 39.92;
					this.camera.position.height = 50000;
					this.animation = true;
					
					this.camera.changed.addEventListener(function(percentage){
						console.log(percentage);
					});

**Comment by zouyaoji** [comment]
哈用 this.viewer.camera或者在cesium-viewer组件上绑定哦@changed
