### ISSUE TITLE
[Bug Report] 请问怎么使用Cesium原生的类和函数？

### ISSUE THREAD

**Issue by DuShuYuan** [zouyaoji/vue-cesium#150]
### VueCesium version
3.0.8

### OS/Browsers version
windows

### Vue version
3.2.30

### Cesium version
1.90.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/bG

### Steps to reproduce
。sdsadasdasd

### What is Expected?
比如创建一个cesium的日期
import Cesium from 'vue-cesium/Cesium'
const d = Cesium.JulianDate.fromDate(new Date())

### What is actually happening?
报错
This dependency was not found:

* vue-cesium/Cesium in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16
/dist??ref--1-1!./src/views/Home.vue?vue&type=script&lang=js

To install it, you can run: npm install --save vue-cesium/Cesium

**Comment by zouyaoji** [comment]
Cesium已经是挂到window了，只需要在ESLint中定义出即可。 可以参考项目：

https://github.com/zouyaoji/vue-cesium-demo

提问请到 Discussions 中讨论。
