### ISSUE TITLE
[Bug Report] 和CesiumVectorTile 一起使用报错

### ISSUE THREAD

**Issue by DuShuYuan** [zouyaoji/vue-cesium#155]
### VueCesium version
3.0.9

### OS/Browsers version
windows

### Vue version
3.2.31

### Cesium version
1.90.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/sdsasasdasd

### Steps to reproduce
在ready函数中加载本地shp文件
```
onViewerReady ({ Cesium, viewer }) {
            
            // eslint-disable-next-line no-unused-vars
            var worldLayer = null
            // eslint-disable-next-line no-unused-vars
            var worldProvider = new VectorTileImageryProvider({
                source: 'http://localhost:1379/map/shp/区域_全球国界.shp',
                defaultStyle: {
                    outlineColor: 'rgb(255,0,0)',
                    lineWidth: 1,
                    fill: false,
                    tileCacheSize: 200,
                    showMaker: false,
                    showCenterLabel: true,
                    fontColor: 'rgba(255,0,0,1)',
                    labelOffsetX: -10,
                    labelOffsetY: -5,
                    fontSize: 13,
                    fontFamily: '黑体',
                    centerLabelPropertyName: 'NAME'
                },
                maximumLevel: 20,
                minimumLevel: 1,
                simplify: false
            })
            worldProvider.readyPromise.then(function () {
                worldLayer = viewer.imageryLayers.addImageryProvider(worldProvider)
            })
        }
```

报错信息：
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'defaultAccessToken')
    at load (webpack-internal:///./node_modules/vue-cesium/es/components/viewer/src/useViewer.mjs:487:28)

### What is Expected?
。。

### What is actually happening?
。。。

**Comment by zouyaoji** [comment]
请提供一个重现的demo我晚上看看。

**Comment by DuShuYuan** [comment]
[testvue3.zip](https://github.com/zouyaoji/vue-cesium/files/8077903/testvue3.zip)


地表高度量算功能咋使用的？还是说功能bug了
<img width="1131" alt="Snipaste_2022-02-16_16-05-29" src="https://user-images.githubusercontent.com/11830896/154221850-0c5467a3-292a-4136-b120-45743d31d4e8.png">
？

**Comment by zouyaoji** [comment]
嗯 高度量算bug了。下个版本修复哈

**Comment by DuShuYuan** [comment]
还有个问题，开发过程中，时间稍微久一点，运行就特别卡，画个线、圈啥的跟幻灯片一样。。。
关闭标签页重新打开也一样，除非关闭浏览器再打开就很流畅了

**Comment by zouyaoji** [comment]
如果你打开在线文档有没有你说的这个情况？

**Comment by zouyaoji** [comment]
@DuShuYuan 我刚看了一下，暂不明咋回事。导入了CesiumVectorTile，Cesium被修改了。
![image](https://user-images.githubusercontent.com/24430116/154308506-56450823-aeef-4b0c-864b-ce19774943f8.png)

**Comment by zouyaoji** [comment]
@DuShuYuan 
我又斟酌了一下，出现这个问题的原因是
导入CesiumVectorTile时候，vue-cesium还没完成初始化，导入时CesiumVectorTile那边就没识别到Cesium对象，
就引了它自带的一个Cesium，而这个Cesium版本比较老，和vue-cesium不兼容。

所以你这儿要保证导入CesiumVectorTile的时候Cesium已经被引入了，就能避免这个问题。提供一个解决办法，在index.html引入Cesium：
```html
<!--
 * @Author: zouyaoji@https://github.com/zouyaoji
 * @Date: 2022-02-17 00:07:14
 * @LastEditTime: 2022-02-17 09:10:09
 * @LastEditors: zouyaoji
 * @Description:
 * @FilePath: \testvue3\public\index.html
-->
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <script src="./Cesium/Cesium.js"></script>
    <link rel="stylesheet" href="./Cesium/Widgets/widgets.css"></link>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>

```

**Comment by DuShuYuan** [comment]
多谢！这样可以了！
index中引入后就不用再等 vcready函数后才能使用cesium类了，这样感觉更好

**Comment by zouyaoji** [comment]
确实哈，不过我也很少这么引用，如果有问题你再另开issue了。
