### ISSUE TITLE
[Bug Report] 绘制组件贴地bug

### ISSUE THREAD

**Issue by DuShuYuan** [zouyaoji/vue-cesium#156]
### VueCesium version
3.0.9

### OS/Browsers version
edge

### Vue version
3.2.31

### Cesium version
1.90.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/xxxxxx

### Steps to reproduce
xxx

### What is Expected?
xx

### What is actually happening?
只有线贴地了，点和填充面 还是没有贴地，浮着的

<img width="1110" alt="bug1" src="https://user-images.githubusercontent.com/11830896/154624850-7c328af0-c50c-42d0-8048-cf160c5393cf.png">

线画的远一点，然后对点拉近镜头，就这样，点是浮着的
<img width="772" alt="bug2" src="https://user-images.githubusercontent.com/11830896/154625013-7ee97d16-95ab-4d5a-8f0a-63078dd16588.png">

**Comment by zouyaoji** [comment]
贴地只处理了 线、面，点没处理哈。

面确实是个bug，下个版本修复哈，谢谢反馈。
