### ISSUE TITLE
[Bug Report] 使用了vc-trail-wall组件后只有颜色围墙，不显示动画

### ISSUE THREAD

**Issue by lanfengcloud** [zouyaoji/vue-cesium#160]
### VueCesium version
2.3.4

### OS/Browsers version
98.0.4758.102

### Vue version
3.2.31

### Cesium version
1.90.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/xfdsafsa

### Steps to reproduce
      <vc-trail-wall
        :positions="positions"
        color="yellow"
        :minimum-heights="minimumHeights"
        image-url="./colors1.png"
        ref="wall"
        :interval="3000"
      ></vc-trail-wall>
图片存储到了本地路径

### What is Expected?
有动画

### What is actually happening?
无动画

**Comment by zouyaoji** [comment]
这是你路径没对的原因哈，不能是相当于硬盘的路径的，得是web服务路径，换句话说你这个图片的地址在你浏览器地址栏输入要能够访问到才行。
