### ISSUE TITLE
[Bug Report] VcDrawings>Pin，billboardOpts.image动态切换，会导致已经画好的点标记图标被切换

### ISSUE THREAD

**Issue by brantroy** [zouyaoji/vue-cesium#167]
### VueCesium version
3.0.10

### OS/Browsers version
win10,firefox

### Vue version
3.2.31

### Cesium version
1.91.0

### Reproduction Link
www.github.com

### Steps to reproduce
先画一些标记点，动态切换pinDrawingOpts.billboardOpts.image属性，会导致已经画好的标记点图标被切换

### What is Expected?
看起来像是options应该clone后再用，不过我不知道应该怎么改，能否告知下如何快速修复这个问题呢

### What is actually happening?
待处理

**Comment by zouyaoji** [comment]
按照目前设计确实是这样的表现。等空了我琢磨一下怎么完善到支持你说的这个要求。

**Comment by brantroy** [comment]
感谢，项目非常好，持续关注中。。。

**Comment by Janjuya** [comment]
这个问题解决了么大佬。。。

**Comment by zouyaoji** [comment]
还没有哈
我抓紧点

**Comment by zouyaoji** [comment]
@Janjuya 
已经可以了，不过我还想把点也搞成可以支持单个改的，再等等吧。

![image](https://user-images.githubusercontent.com/24430116/158020557-13489394-f308-41e9-a08c-de8a726bcdc3.png)

**Comment by Janjuya** [comment]
跪谢大佬

**Comment by Janjuya** [comment]
大佬这个 更新到npm  上了么 版本没有最新的 还是 3.0.10

**Comment by zouyaoji** [comment]
还没有哈 两天之内应该能发一个 还有点内容没改完

**Comment by Janjuya** [comment]
我还希望这个图标和字体能定义大小 😘

**Comment by zouyaoji** [comment]
下个版本
通过 billboardOpts labelOpts pointOpts 修改
![image](https://user-images.githubusercontent.com/24430116/158321509-2ce4ec68-a2cd-46a6-8c64-f4f6a07e6722.png)

//比如 修改第一个绘制图标的属性
drawingsRef.getDrawingActionInstances()[0].cmpRef.value.renderDatas.value[0].billboardOpts.scale = 5

线、面将renderDatas替换为computedRenderDatas找到对应的属性更改。
