### ISSUE TITLE
地图点标记 自定义图标不能被加载到地图上，指定后加载的还是默认的点图标

### ISSUE THREAD

**Issue by Janjuya** [zouyaoji/vue-cesium#168]
pinDrawingOpts: {
          billboardOpts: {
            image: 'https://zouyaoji.top/vue-cesium/images/grepin.png'
          },
          labelOpts: {
            text: '图标点',
            pixelOffset: [0, -60]
          }
        }

**Comment by zouyaoji** [comment]
hi @Janjuya，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
https://github.com/zouyaoji/vue-cesium/issues/167#issue-1160814415
