### ISSUE TITLE
[Bug Report] 如何关闭类型检查错误提示

### ISSUE THREAD

**Issue by webdq** [zouyaoji/vue-cesium#173]
### VueCesium version
3.0.11

### OS/Browsers version
windows

### Vue version
3.2.25

### Cesium version
1.91.0

### Reproduction Link
https://codepen.io/webdq/pen/vYpJoog

### Steps to reproduce
vite2 vue3 ts项目，开启了eslint，使用vue-cesium组件传入props有错误提示

package json文件

[![qfPpQK.png](https://s1.ax1x.com/2022/03/31/qfPpQK.png)](https://imgtu.com/i/qfPpQK)

tsconfig配置

[![qfPlwQ.png](https://s1.ax1x.com/2022/03/31/qfPlwQ.png)](https://imgtu.com/i/qfPlwQ)

eslint配置

[![qfPaOU.png](https://s1.ax1x.com/2022/03/31/qfPaOU.png)](https://imgtu.com/i/qfPaOU)

### What is Expected?
关闭错误提示

### What is actually happening?
props显示的错误提示

[![qfPotA.md.png](https://s1.ax1x.com/2022/03/31/qfPotA.md.png)](https://imgtu.com/i/qfPotA)
[![qfPHpt.md.png](https://s1.ax1x.com/2022/03/31/qfPHpt.md.png)](https://imgtu.com/i/qfPHpt)

**Comment by zouyaoji** [comment]
暂时先as成any哈。

下个版本类型声明就能全部导出了 现在完成了80%了。

**Comment by zouyaoji** [comment]
请尝试 3.0.12版本哈，每个props都有类型声明了。
