### ISSUE TITLE
每次进入组件页面都要重新初始化吗？

### ISSUE THREAD

**Issue by isliqian** [zouyaoji/vue-cesium#18]
vue已经缓存了组件页面，但是每次进入组件页面后，还要进行初始化加载，导致地图崩溃，如何避免每次进入页面初始化加载？

**Comment by zouyaoji** [comment]
这种情况多半是你页面路由切换的时候把放cesium的容器切换了吧。 把cesium容器放一级路由

**Comment by zouyaoji** [comment]
没回复关了哈 有问题再交流
