### ISSUE TITLE
[Bug Report] vue-cesium-vite-starter run pnpm run build can't build successful

### ISSUE THREAD

**Issue by cinos1** [zouyaoji/vue-cesium#180]
### VueCesium version
3.0.11

### OS/Browsers version
win11/edge 100

### Vue version
3.2.31

### Cesium version
1.92.0

### Reproduction Link
https://github.com/zouyaoji/vue-cesium-vite-starter

### Steps to reproduce
git clone https://github.com/zouyaoji/vue-cesium-vite-starter.git
cd vue-cesium-vite-starter
pnpm i
pnpm run build

### What is Expected?
build success

### What is actually happening?
 error TS2307: Cannot find module '@vue-cesium/utils/types' or its corresponding type declarations.

**Comment by zouyaoji** [comment]
fixed, please pull the latest code.Fixed, please pull the latest code.
