### ISSUE TITLE
[Feature Request] 提供全局配置来注入Cesium实例

### ISSUE THREAD

**Issue by moolex** [zouyaoji/vue-cesium#183]
### Existing Component
是

### Component Name
VcConfigProvider

### Description
有时候写一些cesium扩展或者使用其他cesium插件的时候，Ceisum实例不好传递，直接import from cesium是比较简单的方式，但是import获取的Ceisum和vue-ceisum ready里的实例好像不太一样，所以是否可以提供一个参数，让用户自己把import进来的Cesium实例传递给vc-config-provider

**Comment by zouyaoji** [comment]
https://github.com/zouyaoji/vue-cesium/issues/155#issuecomment-1042470701

请参考这个

**Comment by zouyaoji** [comment]
上面那种是直接将 Cesium 搞成全局的了，在vue-cesium初始化之前就是了。

**Comment by zouyaoji** [comment]
如果不想要上面那种，就只有在你扩展的插件里面写一个初始化方法， 等vue-cesium初始化成功之后再去初始化你的插件。
我自己遇到这种情况是这样处理的。

类似这样：
![image](https://user-images.githubusercontent.com/24430116/161921504-31ef6b1f-f9a2-4432-97e6-1af6d921bd5d.png)

**Comment by moolex** [comment]
感谢！

我发现是我用了vite-plugin-ceisum但是它的js在dev模式下没有自动载入，导致dev下需要手动import，但是build之后又会在index.html里增加Ceisum.js的加载，我通过在index.html里加载Cesium.js就不会触发vue-ceisum再加载ceisum实例了
