### ISSUE TITLE
[Bug Report] 百度地图图层经常刷不出来，尤其是影像地图

### ISSUE THREAD

**Issue by 651778286** [zouyaoji/vue-cesium#187]
### VueCesium version
3.0.11

### OS/Browsers version
Windows 10 21H2 / Chrome 100.0.4896.75

### Vue version
3.2.25

### Cesium version
1.92.0

### Reproduction Link
https://codepen.io/651778286/pen/BaJVrLz

### Steps to reproduce
1、直接打开连接进入codepen实例
2、左侧“切换服务”选择“百度影像”
3、缩小放大地图查看影像地图加载效果

### What is Expected?
影像地图正常且迅速地加载

### What is actually happening?
影像地图加载很慢，设置很多图片块加载失败

**Comment by zouyaoji** [comment]
影像服务不支持 https 服务，你本地把用影像的时候要改成 http，如果实在要用https 就上前端代理哈。
