### ISSUE TITLE
Error in mounted hook: "TypeError: this._Cesium(...) is undefined"

### ISSUE THREAD

**Issue by ristona** [zouyaoji/vue-cesium#19]
<template>
  <div class="home">
     <cesium-viewer @ready="ready">
        <imagery-layer>
          <bingmaps-imagery-provider url="https://dev.virtualearth.net" bmKey="AgcbDCAOb9zMfquaT4Z-MdHX4AsHUNvs7xgdHefEA5myMHxZk87NTNgdLbG90IE-" mapStyle="Aerial"/>
        </imagery-layer>
        <cesium-terrain-provider :requestWaterMask="requestWaterMask"></cesium-terrain-provider>
      </cesium-viewer>
  </div>
</template>

<script>
import { Component, Vue } from 'vue-property-decorator';

export default {
  data () {
        return {
          requestWaterMask: true
        }
      },
      methods: {
        ready (cesiumInstance) {
          const {Cesium, viewer} = cesiumInstance
          var target = new Cesium.Cartesian3(300770.50872389384, 5634912.131394585, 2978152.2865545116)
          var offset = new Cesium.Cartesian3(6344.974098678562, -793.3419798081741, 2499.9508860763162)
          viewer.camera.lookAt(target, offset)
          viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY)
        }
      }
}
</script>

**Comment by ristona** [comment]
不能使用全局注册，改为局部注册可以使用
import CesiumViewer from 'vue-cesium/src/components/viewer/CesiumViewer';

**Comment by zouyaoji** [comment]
你全局注册怎么写的 贴出来看看？

**Comment by ristona** [comment]
在main.js文件中
`import VueCesium from 'vue-cesium';
// Vue-Cesium will load Cesium.js from `https://unpkg.com/cesium/Build/Cesium/Cesium.js`
Vue.use(VueCesium);
`

**Comment by zouyaoji** [comment]
用的是1.0.3版本吗？

**Comment by ristona** [comment]
是的，感觉跟TS环境有关。因为在VS CODE中点击“import VueCesium from 'vue-cesium'”打开了
index.d.ts文件

**Comment by zouyaoji** [comment]
你用的ts啊，我还没测过ts，估计有问题...

**Comment by ristona** [comment]
是啊，ts开发类挺方便的，这就是我为何建议把相关配置改为JS代码配置，而不是VUE风格配置。

**Comment by zouyaoji** [comment]
ts看后续吧，听说cesium在重构，要是他本身就支持ts了应该就好办了？我目前还没开发过ts的库。。。
