### ISSUE TITLE
[Feature Request] can rotate compass directly to rotate Cesium View in 2D mode?（2D模式下可以直接转动Compass来转动视图吗？）

### ISSUE THREAD

**Issue by BoatingZeng** [zouyaoji/vue-cesium#193]
### Existing Component
是

### Component Name
Compass

### Description
期望：

1、在2D模式（SCENE2D）下，可以直接转动Compass，来旋转Cesium视图

是有什么特殊原因不能这样做吗？

谢谢

English------------------------------------------------------------------------

expect：

1、in 2D mode（SCENE2D），can rotate the compass to rotate Cesium View

Is there any reason we can`t do that?

Thanks

**Comment by zouyaoji** [comment]
I looked at the official sandbox example, the 2D view does not support changing the camera pitch and rotation parameters. Only 3D View and Columbus View are supported.

我看了一下官方沙盒例子，2D视图不支持改变相机俯仰、旋转参数。只有3D视图和哥伦布视图支持。
