### ISSUE TITLE
[Bug Report]    Moon sphere related issues（ArcGIS Spatial Reference 104903 ）

### ISSUE THREAD

**Issue by weilb** [zouyaoji/vue-cesium#196]
### VueCesium version
3.0.12

### OS/Browsers version
Google  100.0.4896.127

### Vue version
2.6.1

### Cesium version
1.92.0

### Reproduction Link
https://codepen.io/weilb/pen/eYyqNXg

### Steps to reproduce
Copy the HTML content in https://codepen.io/weilb/pen/eYyqNXg, paste to a separate HTML file, double-click to open.  
Problem one: Click the navigation control to enlarge the button, found that it will flash, no zoom  
Problem two: the mouse moves on the moon sphere, real-time longitude and latitude coordinates display bar (lower right corner) longitude range should be 0~360, latitude range should be 0~90, the current range of 0~180, latitude seems to be wrong  

### What is Expected?
Click the zoom button of the navigation control to reduce the camera height normally (similar to zoom scale)
The mouse moves on the moon sphere, real-time longitude and latitude coordinates display bar (lower right corner) longitude range should be in 0~360, latitude range should be in 0~90

### What is actually happening?
Problem 1: Click the navigation control to enlarge the button, found that it will flash, no zoom
Problem two: the mouse moves on the moon sphere, real-time longitude and latitude coordinates display bar (lower right corner) longitude range should be 0~360, latitude range should be 0~90, the current range of 0~180, latitude seems to be wrong

**Comment by zouyaoji** [comment]
The problem was not reproduced with the latest Cesium version. The longitude and latitude display range of statusbar is 0-180, which is distinguished by east-west longitude.
