### ISSUE TITLE
createTileMapServiceImageryProvider is deprecated and will be removed in Cesium 1.65. Please use TileMapServiceImageryProvider instead.

### ISSUE THREAD

**Issue by ristona** [zouyaoji/vue-cesium#20]
`<template>
  <div class="home">
        

     <cesium-viewer @ready="ready">
        <imagery-layer>
          <bingmaps-imagery-provider url="https://dev.virtualearth.net" bmKey="AgcbDCAOb9zMfquaT4Z-MdHX4AsHUNvs7xgdHefEA5myMHxZk87NTNgdLbG90IE-" mapStyle="Aerial"/>
        </imagery-layer>
        <cesium-terrain-provider :requestWaterMask="requestWaterMask"></cesium-terrain-provider>
      </cesium-viewer>
  </div>
</template>

<script>
import CesiumViewer from 'vue-cesium/src/components/viewer/CesiumViewer';
import ImageryLayer from 'vue-cesium/src/components/imageryLayers/ImageryLayer';
import BingmapsImageryProvider from 'vue-cesium/src/components/imageryLayers/BingMapsImageryProvider';
import CesiumTerrainProvider from 'vue-cesium/src/components/terrains/CesiumTerrainProvider';

export default {
  components: {CesiumViewer, ImageryLayer, BingmapsImageryProvider,CesiumTerrainProvider},
  data () {
        return {
          requestWaterMask: true
        }
      },
      methods: {
        ready (cesiumInstance) {
          const {Cesium, viewer} = cesiumInstance
          var target = new Cesium.Cartesian3(300770.50872389384, 5634912.131394585, 2978152.2865545116)
          var offset = new Cesium.Cartesian3(6344.974098678562, -793.3419798081741, 2499.9508860763162)
          viewer.camera.lookAt(target, offset)
          viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY)
        }
      }
}
</script>
`

**Comment by zouyaoji** [comment]
Cesium 1.65版本createTileMapServiceImageryProvider改成了TileMapServiceImageryProvider了啊，我更新一下，谢谢反馈。

**Comment by ristona** [comment]
建议不要动态加载Cesium，使用依赖包方式，这样就可以避免版本升级带来的问题。若需优化，开发人员可以自行配置WebPack来解决这个问题。

收到。请尽快发布最新版本，谢谢！

**Comment by zouyaoji** [comment]
我刚看了，现在Cesium最新1.62呢，等他更新到1.65的时候我这边修改了就OK了，先当成警告，不影响使用。

**Comment by zouyaoji** [comment]
我这项目从开始就决定用动态加载Build后的Cesium包。主要是考虑以下几点：
1、Cesium本身有点庞大，静态资源也很多，依赖包引入工程比较大了，打包慢，动态引入用在线或者本地的都可以，而且很快的。
2、用依赖包的话几乎没法引入那些在Cesium基础上开发的第三方产品，动态引入的话不受版本限制，且可以自主选择用原生Cesium或者第三方Cesium产品。

如果你要用依赖包的形式，参考官方webpack引入cesium的方式即可。[传送门](https://cesium.com/docs/tutorials/cesium-and-webpack/)
