### ISSUE TITLE
建议将ImageryProvider等Vue Component改为配置

### ISSUE THREAD

**Issue by ristona** [zouyaoji/vue-cesium#21]
我猜测你将ImageryProvider等设计为Compoent是为了便于配置不同数据源。若使用一个options对象来配置感觉更好一些。可参考vue-video-play。它也是为了支持MP4,RTMP,HLS等不同视频格式，与你的场景有些类似。

**Comment by zouyaoji** [comment]
我这是为了和原生Cesium API接口属性尽量保持一致哈。

**Comment by zouyaoji** [comment]
最近在重构2.0版本，我又考虑了一下你说的支持用options，但并发现不是那么方便，因为不同的ImageryProvider差异还是比较大的，不太好把所有 ImageryProvider 都归纳到一个通用的 options 中...
