### ISSUE TITLE
[Bug Report] css中得disabled 得cursor:not-allowed!important

### ISSUE THREAD

**Issue by yanglinyu-Jason** [zouyaoji/vue-cesium#216]
### VueCesium version
3.0.13

### OS/Browsers version
windows

### Vue version
3.2.33

### Cesium version
1.94.2

### Reproduction Link
https://github.com/zouyaoji/vue-cesium-demo

### Steps to reproduce
css中得得disable 污染到全局变量了

### What is Expected?
期望修复，或者给个解决办法

### What is actually happening?
期望修复，或者给个解决办法

**Comment by zouyaoji** [comment]
没明白

**Comment by yanglinyu-Jason** [comment]
![image](https://user-images.githubusercontent.com/30770752/175498134-5a7309fa-2f75-4760-b6b4-afdf986e2e18.png)
css中得这个污染到影响到全局了

我昨天得问题已经解决，你们可以酌情修复

**Comment by zouyaoji** [comment]
理解了，还是麻烦你避免一下吧。

1、你避免使用 disabled 这个class 名...
2、你自己定在导入vue-cesium的 css 之前 重置一下这个class名的样式
