### ISSUE TITLE
不支持FireFox

### ISSUE THREAD

**Issue by ristona** [zouyaoji/vue-cesium#22]
Firefox 版本：71.0b1
vue代码：
`     <cesium-viewer>
       
     </cesium-viewer>`
错误提示：
`Visit http://get.webgl.org to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:
RuntimeError: The browser supports WebGL, but initialization failed.
t@https://unpkg.com/cesium/Build/Cesium/Cesium.js:472:5514
z@https://unpkg.com/cesium/Build/Cesium/Cesium.js:525:29546
Ce@https://unpkg.com/cesium/Build/Cesium/Cesium.js:551:27033
P@https://unpkg.com/cesium/Build/Cesium/Cesium.js:560:8933
ee@https://unpkg.com/cesium/Build/Cesium/Cesium.js:562:30079
init@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-cesium/src/components/viewer/CesiumViewer.vue?vue&type=script&lang=js&:876:20
initViewer@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-cesium/src/components/viewer/CesiumViewer.vue?vue&type=script&lang=js&:930:12
`

**Comment by zouyaoji** [comment]
我刚下载了个最新的火狐没问题啊，但也才69.0.3啊，你这71的版本咋来的。。
![image](https://user-images.githubusercontent.com/24430116/67059741-cbe4dd80-f18c-11e9-850c-a6d8905a32a3.png)
