### ISSUE TITLE
[Bug Report] 测绘面积无法取消,并且点击报错

### ISSUE THREAD

**Issue by tzf757329028** [zouyaoji/vue-cesium#246]
### VueCesium version
3.0.16

### OS/Browsers version
window10

### Vue version
3.2.37

### Cesium version
1.96.0

### Reproduction Link
https://github.com/zouyaoji/vue-cesium

### Steps to reproduce
测绘面积无法取消,并且点击报错Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scaleToGeodeticSurface')
官网也有该问题

### What is Expected?
期望修复，或者给个解决办法

### What is actually happening?
期望修复，或者给个解决办法

**Comment by zouyaoji** [comment]
https://zouyaoji.top/vue-cesium/#/zh-CN/component/analyses/vc-drawings

未能够重现。

**Comment by tzf757329028** [comment]
打错字了.是vue2的量算面积 https://zouyaoji.top/vue-cesium-v2/#/zh/tool/vc-measuring

**Comment by zouyaoji** [comment]
2.3.13版本已修复。

建议换到vue3版本。 年底默认就切换到vue3版本了，vue2版本的不维护了。
