### ISSUE TITLE
vue3中，在设置地图为2D状态时，水平、垂直、折线距离测算结果均不会在地图上显示

### ISSUE THREAD

**Issue by wenrenfangge** [zouyaoji/vue-cesium#261]
如图
![image](https://user-images.githubusercontent.com/28972513/185871882-722b40dc-f6e6-4cd2-ba66-6ff885026a5b.png)

**Comment by zouyaoji** [comment]
hi @wenrenfangge，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
用最新版的 vue-cesium和cesium测试哈。如果确实有问题请按规范提 issue，并提供复现用例。
