### ISSUE TITLE
[Bug Report] 加载影像图报错

### ISSUE THREAD

**Issue by wildTechnician** [zouyaoji/vue-cesium#269]
### VueCesium version
3.0.5

### OS/Browsers version
win10

### Vue version
3.2.16

### Cesium version
1.96.0

### Reproduction Link
https://codepen.io/pen?&prefill_data_id=d892285d-0740-4e69-afab-660627abc410

### Steps to reproduce
报错提示:Failed to load resource: net::ERR_BLOCKED_BY_CLIENT。官网相同！

**Comment by zouyaoji** [comment]
链接打开空白，确认有正确提 issue 吗？

**Comment by zouyaoji** [comment]
长期无反馈，直接关闭啦。
