### ISSUE TITLE
cesium-viewer 的 camera 在 sceneMode 2 下的问题

### ISSUE THREAD

**Issue by z4none** [zouyaoji/vue-cesium#27]
当设置 viewer 为 2D 模式时，如果想通过以下方式实时获取 camera 位置，会导致视角卡在错误的位置
```
<cesium-viewer :logo="false" :sceneMode="2" :camera.sync="camera">
  <imagery-layer :contrast="0.8" :saturation="0.8" :brightness="0.5">
    <urltemplate-imagery-provider :url="url"></urltemplate-imagery-provider>
  </imagery-layer>
</cesium-viewer>
<div>
  camera: {{ camera }}
</div>
```
经分析是由于组件 emit 的 camera 数据不兼容 2D 模式导致的的
目前可以通过手动处理 `@update:camera` 来避免，希望能在组件中对 2D 的摄像头位置增加判断

```
<cesium-viewer :logo="false" :sceneMode="2" :camera="camera" @update:camera="onUpdateCamera">
  <imagery-layer :contrast="0.8" :saturation="0.8" :brightness="0.5">
    <urltemplate-imagery-provider :url="url"></urltemplate-imagery-provider>
  </imagery-layer>
</cesium-viewer>
<div>
  camera: {{ camera }}
</div>

...
methods: {
  onUpdateCamera() {
      const camPos = viewer.camera.positionCartographic;
      this.camera.position = {
        lng: camPos.longitude * (180 / Math.PI),
        lat: camPos.latitude * (180 / Math.PI),
        height: camPos.height
      }
    },
}
```

**Comment by zouyaoji** [comment]
问题我重现了，但我看相机结构2D和3D应该差不多，查了一下好像是Cesium已知缺陷，而且很久了都没解决， https://github.com/AnalyticalGraphicsInc/cesium/issues/4246#issue-173801787 和 https://github.com/AnalyticalGraphicsInc/cesium/issues/2469#issue-56582956。我再看看有没有解决方案，不行的话避免一下吧。像你这个改是没问题的，但是我还没搞清楚为啥这样就可以了，我再学习一下先。。。

**Comment by zouyaoji** [comment]
额 好像明白了，是因为 $emit 出来的相机位置不正确，然后设置的时候设了一个错误的位置，然后乱串了吧。

**Comment by zouyaoji** [comment]
Cesium.Cartographic.fromCartesian(viewer.camera.position) 这个方法在二维下面得到的结果不对，具体为啥不对我没去搞明白- -
参考你的代码用 viewer.camera.positionCartographic二维三维都正确，已修改，谢谢反馈。
