### ISSUE TITLE
md-select和imageryProviderMixin.js中的mount方法执行

### ISSUE THREAD

**Issue by bubinyang** [zouyaoji/vue-cesium#28]
最近在阅读您的源码，想请教一下，影像模块中md-select组件如何引入的？刷新页面，imageryProviderMixin.js中的mount方法是怎么触发执行的？

**Comment by zouyaoji** [comment]
你好，可以看一下dev分支，即将发布的2.0版本我重构了一下，逻辑更清晰了，注释也比较详尽。

**Comment by bubinyang** [comment]
先告诉我怎么做到的嘛，我就当阅读学习，dev再说嘛

**Comment by zouyaoji** [comment]
md-select组件是文档用的一个界面组件。 叫`vue-material`  具体是在 docs/main.js 里面加载的。
