### ISSUE TITLE
[Bug Report] 单词拼写错误: retangle 应为 rectangle

### ISSUE THREAD

**Issue by liuqun** [zouyaoji/vue-cesium#291]
### VueCesium version
受影响的版本为：从vue-cesium@3.0.7至3.1.0之间的版本

关联的文件：`cZoomControl`控件和`cesium-helpers.ts`
### OS/Browsers version
任意

### Vue version
3.2.41

### Cesium version
1.98.1

### Reproduction Link
https://github.com/zouyaoji/vue-cesium/blob/b79e08a8ff619a9ab7996f7de5919d158de70547/packages/utils/types.ts#L186-L192

### Steps to reproduce
vue-cesium/packages/utils/types.ts

发现一处单词拼写错误: retangle 应为 rectangle

https://github.com/zouyaoji/vue-cesium/blob/b79e08a8ff619a9ab7996f7de5919d158de70547/packages/utils/types.ts#L188
https://github.com/zouyaoji/vue-cesium/blob/b79e08a8ff619a9ab7996f7de5919d158de70547/packages/utils/cesium-helpers.ts#L806

### What is Expected?
应为 rectangle

### What is actually happening?
笔误写成了 `retangle`

**Comment by liuqun** [comment]
https://github.com/zouyaoji/vue-cesium/search?q=retangle&type=code

与此处笔误相关联的文档手册也应一并修改：
https://github.com/zouyaoji/vue-cesium/blob/1998480c3ab6468cdbd61f17a8a0b30ac488da86/website/docs/zh-CN/base.md#L196
https://github.com/zouyaoji/vue-cesium/blob/1998480c3ab6468cdbd61f17a8a0b30ac488da86/website/docs/en-US/base.md

**Comment by zouyaoji** [comment]
已收到，感谢反馈。
