### ISSUE TITLE
引用第三方cesium插件报错

### ISSUE THREAD

**Issue by DLFouge** [zouyaoji/vue-cesium#3]
使用npm install cesium-navigation --save安装后在vue中进行如下引用：

import Cesium from 'cesium/Cesium'; 
import  widgets from'cesium/Widgets/widgets.css';
import '../../node_modules/cesium-navigation/navigation.js';

//指北针插件
    viewer.extend(Cesium.viewerCesiumNavigationMixin, {});

然后浏览器报错：
  Uncaught Error: No ../lib/weakmap                                       navigation.js?946e:114
    at callDep (navigation.js?946e:114)
    at req (navigation.js?946e:213)
    at v (navigation.js?946e:3091)
    at eval (navigation.js?946e:3105)
    at Object.eval (navigation.js?946e:3106)
    at eval (navigation.js?946e:4)
    at Object.eval (navigation.js?946e:7)
    at eval (navigation.js:11906)
    at Object../node_modules/cesium-navigation/navigation.js (app.js:1056)
    at __webpack_require__ (app.js:679)
不知道怎么截图显示不出来

**Comment by DLFouge** [comment]
这个项目下来下来后npm install怎么报错？在本地应该怎么运行？

**Comment by zouyaoji** [comment]
嗨，看你代码，感觉你没有用到我这个项目呢。。。 
直接import打包后的cesium有问题才弄了这个项目。
import VueCesium from 'vue-cesium'
Vue.use(VueCesium, {
  // cesiumPath 是指引用的Cesium.js路径，如
  // 项目本地的Cesium Build包，vue项目需要将Cesium Build包放static目录：
  // ./static/Cesium/Cesium.js
})

**Comment by DLFouge** [comment]
现在我自己想要搭建一个类似你这样的vue+cesium的项目，但是不知道怎么做，你能给我个搭建文档参考一下 么

**Comment by DLFouge** [comment]
这个项目下载下来后npm install怎么报错，npm i --save vue-cesium这个也报错，不知道怎么 跑起来

**Comment by zouyaoji** [comment]
npm i --save vue-cesium 报错可能你环境有问题了吧？检查网络啥的。

**Comment by zouyaoji** [comment]
这样吧，你新建一个vue模板项目，引入vue cesium，要是不会你截图一步一步给你说，你就这样说我也不晓得你问题在哪。

**Comment by DLFouge** [comment]
我搭好vue项目后，在该文件下引入npm i --save vue-cesium 就可以了么

**Comment by zouyaoji** [comment]
是的，我感觉你可能理解错了vue-cesium只是一个帮你把Cesium（这个Cesium是Build出来的包，可以是你自己的，也可以是超图的，也可以是官方的，地址可以是本地的，也可以是在线的，很灵活的）引入到vue项目的Vue工具，并不是一个我在Cesium上再开发出来的东西。

**Comment by DLFouge** [comment]
那引入这个之后我可以直接用本地的build包，不用在用官方的么

**Comment by zouyaoji** [comment]
可以的啊。但是包的位置不能随便放，需要放静态目录下。比如vue cli的项目，就是放一个static的文件夹里面。

**Comment by DLFouge** [comment]
![image](https://user-images.githubusercontent.com/26078841/48929271-209eba80-ef22-11e8-8997-f9d914d133fd.png)
安装完了，我后面还需要配置哪些文件

**Comment by zouyaoji** [comment]
看这个，操作一下哈。
https://github.com/zouyaoji/vue-cesium/blob/master/README.zh.md

**Comment by DLFouge** [comment]
我想看一下你这个项目的效果，下载下来后应该怎么操作

**Comment by zouyaoji** [comment]
有在线地址可以看啊：
https://zouyaoji.top/vue-cesium/#/

**Comment by DLFouge** [comment]
https://github.com/zouyaoji/vue-cesium/blob/master/README.zh.md
我按这个配置了，还是有错误，不知道是不是配置写错了文件，这个上面的配置应该放在那个文件下？
