### ISSUE TITLE
[Bug Report] VcNavigation组件ready事件{cesiumObject}参数问题

### ISSUE THREAD

**Issue by kkwwang** [zouyaoji/vue-cesium#309]
### VueCesium version
3.1.1

### OS/Browsers version
win11，edge

### Vue version
3.2.40

### Cesium version
1.99.0

### Reproduction Link
https://codepen.io/kkwwang/pen/MWXevqY

### Steps to reproduce
无

### What is Expected?
返回dom元素

### What is actually happening?
返回了[null, null]

**Comment by zouyaoji** [comment]
下个版本直接把 ref 模板引用出去。
![image](https://user-images.githubusercontent.com/24430116/200027748-25f13783-578e-42a2-8efc-f9607fa08002.png)
