### ISSUE TITLE
[Feature Request] 使用火星科技的 Cesium 库时，如何通过 useVueCesium 函数获取 map实例？

### ISSUE THREAD

**Issue by caixiaoguang** [zouyaoji/vue-cesium#313]
### Existing Component
Yes

### Component Name
VcViewer

### Description
使用火星科技的 Cesium 库时，VcViewer 的子组件内调用 useVueCesium 函数返回的对象没有 map 实例，请问这个要怎么获取？

**Comment by zouyaoji** [comment]
目前确实没有设计这一块，
我先想想，后续加一下。再我加之前你先自己在vc-viewer 的 ready 事件中保存一下吧。
