### ISSUE TITLE
viewer.flyto方法如何将封装好的VcDatasourceCustom作为参数

### ISSUE THREAD

**Issue by 1061875478** [zouyaoji/vue-cesium#318]
请问viewer.flyto怎样将视角转向VcDatasourceCustom，viewer.flyto只支持cesium的原生对象

**Comment by zouyaoji** [comment]
hi @1061875478，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
