### ISSUE TITLE
[Bug Report] flyto无法将封装好的VcDatasourceCustom或者实体作为参数

### ISSUE THREAD

**Issue by 1061875478** [zouyaoji/vue-cesium#319]
### VueCesium version
3.1.1

### OS/Browsers version
win11

### Vue version
3.2.45

### Cesium version
1.99.0

### Reproduction Link
https://codepen.io/1061875478/pen/ZERagKd

### Steps to reproduce
创建一个vcEntity并赋予ref属性，之后使用viewer.flyto将该Entit对象作为参数

### What is Expected?
应该视角转向实体

### What is actually happening?
没有反应

**Comment by zouyaoji** [comment]
通过 ready事件或者ref模板引用得到 cesiumObject(数据源)，然后flyTo(cesiumObject)

如果要飞Entity，通过数据源api获取即可。

**Comment by 1061875478** [comment]
感谢，可以使用了
