### ISSUE TITLE
[Feature Request] 绘制点位调整

### ISSUE THREAD

**Issue by Mrjzf** [zouyaoji/vue-cesium#322]
### Existing Component
是

### Component Name
vc-handler-draw-point

### Description
大佬，绘制点位可否使用billboard，传自定义图标？而且现在mode=1状态下，如果不点击右键结束，左键点击是一直可以绘制的。返回的positions可否是经纬度和高度，不然还要转换，可以加个配置。第一次使用，感谢大佬！

**Comment by zouyaoji** [comment]
你好，请使用vue3版本组件。

vue2 版本的组件不会增加新功能了。如果确实需要，可以参考 `vc-handler-draw-point` 源码自己写一个绘制billboard的。

**Comment by Mrjzf** [comment]
好的，多谢
