### ISSUE TITLE
[Feature Request] Change language for whole app

### ISSUE THREAD

**Issue by tika-iteratec** [zouyaoji/vue-cesium#363]
### Existing Component
Yes

### Component Name
vc-measurements

### Description
Hi,
how can you change the language of the measurement tools and the location bar?

I changed the map language by adding `locale: enUS` in the main.js file.

Thanks

**Comment by zouyaoji** [comment]
https://zouyaoji.top/vue-cesium/#/en-US/component/vc-config-provider

https://github.com/zouyaoji/vue-cesium-demo/blob/main/src/components/viewer/Index.vue#L10
