### ISSUE TITLE
用vue3最新框架，选择ts，vite打包的时候，源码里面报错

### ISSUE THREAD

**Issue by Wd13869167203** [zouyaoji/vue-cesium#375]
### Discussed in https://github.com/zouyaoji/vue-cesium/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **Wd13869167203** April  4, 2023</sup>
这是报错信息
![image](https://user-images.githubusercontent.com/31448471/229763306-73c31f1f-18d1-4300-a4d6-bf322b4493e3.png)
</div>

**Comment by zouyaoji** [comment]
hi @Wd13869167203，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
