### ISSUE TITLE
[Feature Request] VcDrawings组件如何绘制分支线段

### ISSUE THREAD

**Issue by dishpzga** [zouyaoji/vue-cesium#391]
### Existing Component
是

### Component Name
VcDrawings

### Description
VcDrawings组件绘制线段时 如何通过现有线段的某个顶点出发绘制新的分支线段？

![image](https://github.com/zouyaoji/vue-cesium/assets/7678040/996f5e94-ca16-4736-9aea-45ee17ef02dc)

**Comment by zouyaoji** [comment]
不支持这种
