### ISSUE TITLE
vue3使用keep-alive时，切换切换Cesium报错

### ISSUE THREAD

**Issue by 95mff** [zouyaoji/vue-cesium#395]
An error occurred while rendering. Rendering has stopped.
TypeError: Cannot destructure property 'defined' of 'Cesium' as it is undefined.

**Comment by zouyaoji** [comment]
hi @95mff，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!

**Comment by 95mff** [comment]
![image](https://github.com/zouyaoji/vue-cesium/assets/31397524/82842aae-5bb2-420e-a04e-f899c190fe22)

**Comment by zouyaoji** [comment]
vc-viewer加一个 :removeCesiumScript="false" 试试
