### ISSUE TITLE
超图的webgl移动端无法使用导航按钮

### ISSUE THREAD

**Issue by lilu0826** [zouyaoji/vue-cesium#4]
移动端无法使用导航按钮

**Comment by zouyaoji** [comment]
嗨，我看了，报错如图：
![image](https://user-images.githubusercontent.com/24430116/50480855-7a127180-0a19-11e9-9f08-8fcdcee224c1.png)
这玩意儿是Cesium.js报错，看不到源代码没招哈。不过我用超图的范例代码，排查测试了一下，只要把jQuery引用去掉了，也能重现这个问题。所以你只需要在你的项目中引入jQuery就能用了，我的在线范例加了这句就能正常使用了。[点我用手机浏览测试。](https://zouyaoji.top/vue-cesium/#/zh/Layers/supermap-imagery-provider)
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
```
还是有80kb，不介意的话先这么用着。
我也很纳闷为啥PC端不引用jQuery就能正常用，移动端要引入jQuery才能正常使用，建议你咨询一下超图，如果知道答案了还希望分享一下。

**Comment by zouyaoji** [comment]
@lilu0826 没问题我就关了哦
