### ISSUE TITLE
[Bug Report] 聚类图元鼠标事件无效

### ISSUE THREAD

**Issue by MangMax** [zouyaoji/vue-cesium#405]
### VueCesium version
3.2.0

### OS/Browsers version
windwos11

### Vue version
3.3.4

### Cesium version
1.107.0

### Reproduction Link
https://codepen.io/1061875478/pen/QWJGazN?editors=1111

### Steps to reproduce
添加聚类图元和click，mouseover事件

### What is Expected?
打印出当前鼠标事件触发的对象

### What is actually happening?
无反应

**Comment by zouyaoji** [comment]
你好，试试搭配 `vc-selection-indicator` 组件。

**Comment by MangMax** [comment]
> 你好，试试搭配 `vc-selection-indicator` 组件。
vc-selection-indicator无法响应鼠标悬停、移入移出事件

**Comment by zouyaoji** [comment]
好的 我抽空加一下，下个版本应该能搞好这个。

**Comment by zouyaoji** [comment]
@MangMax 3.2.1版本已修复。
