### ISSUE TITLE
[Bug Report] primitive重叠时，mouseover和mouseout事件不触发

### ISSUE THREAD

**Issue by MangMax** [zouyaoji/vue-cesium#407]
### VueCesium version
3.2.0

### OS/Browsers version
Windows11

### Vue version
3.3.4

### Cesium version
1.107.0

### Reproduction Link
https://codepen.io/1061875478/pen/NWEwGJP

### Steps to reproduce
鼠标在两个primitive之间来回移动

### What is Expected?
每次移入移出都应该触发事件

### What is actually happening?
只有当鼠标完全移出两个primitive时鼠标事件才会触发

**Comment by zouyaoji** [comment]
我想想看看，重叠时可能没啥好办法哦。

**Comment by MangMax** [comment]
> 我想想看看，重叠时可能没啥好办法哦。

感谢

**Comment by zouyaoji** [comment]
你好，我跟踪了一下，其实支持的，但vue-cesium里面针对这种逻辑是通过拾取对象的id来判断的。https://github.com/zouyaoji/vue-cesium/blob/dev/packages/composables/use-events/index.ts#L106

所以在你给的例子里面只需要在2个 `vc-geometry-instance` 上面分别绑定不同的id即可。
