### ISSUE TITLE
[Bug Report] KMZ files are not rendering using vc-datasource-kml

### ISSUE THREAD

**Issue by sachinsbgithub** [zouyaoji/vue-cesium#410]
### VueCesium version
3.2.0

### OS/Browsers version
All browsers

### Vue version
3.3.4

### Cesium version
1.107.0

### Reproduction Link
https://codepen.io/sachinsbgithub/pen/zYMpxJa

### Steps to reproduce
Steps to reproduce

### What is Expected?
Kmz data to be rendered properly 

### What is actually happening?
getting error
Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'https://unpkg.com/cesium@latest/Build/Cesium/ThirdParty/Workers/z-worker-pako.js' cannot be accessed from origin 'https://zouyaoji.top'.
    at o (https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js:8315:435867)
    at dKe (https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js:8315:435582)
    at LV (https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js:8315:435167)
    at NV (https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js:8315:436836)
    at _j.getData (https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js:8315:445430)
    at async Promise.all (index 0)

**Comment by zouyaoji** [comment]
It has been reproduced, I will find time to solve it.

**Comment by zouyaoji** [comment]
When you use a web worker, the browser loads the worker script from a separate file or URL. However, web workers have a security restriction known as the "same-origin policy." This policy means that web workers can only be loaded from the same domain, protocol, and port as the main page that's requesting them. If you try to load a web worker from a different domain, you will encounter the error you mentioned.

Host the worker script on your server: Download the  Cesium script and host it on your own server. This way, both the main page and the worker script will be from the same origin, and the error should go away.

**Comment by sachinsbgithub** [comment]
Thank you for your response
