### ISSUE TITLE
[Bug Report] 加载 Cesium 格式地形 VcTerrainProviderCesium报错

### ISSUE THREAD

**Issue by zhonghua929** [zouyaoji/vue-cesium#414]
### VueCesium version
3.2.0

### OS/Browsers version
win10/谷歌浏览器

### Vue version
3.3.4

### Cesium version
1.107.2

### Reproduction Link
https://zouyaoji.top/vue-cesium/#/zh-CN/component/providers/vc-terrain-provider-cesium

### Steps to reproduce
vc-terrain-provider-cesium 组件的基础用法，无法显示地形

### What is Expected?
显示地形

### What is actually happening?
无法显示地形报错terrainProvider.readyPromise is undefined

**Comment by zouyaoji** [comment]
这个问题已修复，但还有其他问题没解决，暂时无法更新，在这之前请通过指定cesiumPath锁定1.107之前的版本使用。

**Comment by zouyaoji** [comment]
已在3.2.1版本修复.

Fixed in version 3.2.1.
