### ISSUE TITLE
[Bug Report] 希望在“墙”上增加上下流动的光效或者流动效果

### ISSUE THREAD

**Issue by king2088** [zouyaoji/vue-cesium#423]
### VueCesium version
3.2.1

### OS/Browsers version
windows/chrome

### Vue version
3.3.4

### Cesium version
1.108.0

### Reproduction Link
https://codepen.io/pen?&prefill_data_id=b8e0f890-ae47-4b7e-bd98-df0e7489e460

### Steps to reproduce
在官方文档中，墙的效果中并无流动效果，希望能够增加墙的上下流动效果
https://zouyaoji.top/vue-cesium/#/zh-CN/component/graphics/vc-graphics-wall

### What is Expected?
就像如下这样的动画效果
![2](https://github.com/zouyaoji/vue-cesium/assets/20067250/e688a5f6-072e-414d-9701-27c4637e9009)

### What is actually happening?
目前官方“墙”并无动画效果

**Comment by zouyaoji** [comment]
你那有没有这个效果的材质？有的话加进去即可，类似这个。

![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/3eb9108b-a6f2-4a7c-bd19-c5ea6de0c835)

**Comment by king2088** [comment]
> 你那有没有这个效果的材质？有的话加进去即可，类似这个。
> 
> ![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/3eb9108b-a6f2-4a7c-bd19-c5ea6de0c835)
> 

谢谢你的解答，我没有此类效果材质

**Comment by zouyaoji** [comment]
那你这哪儿看的  我们回头看看能不能参考一下

**Comment by king2088** [comment]
> 那你这哪儿看的  我们回头看看能不能参考一下

http://mars3d.cn/editor-vue.html?id=graphic/primitive/wall

**Comment by zouyaoji** [comment]
@king2088 
3.2.2版本加了
参考
https://zouyaoji.top/vue-cesium/#/zh-CN/component/datasources/vc-datasource-custom

https://zouyaoji.top/vue-cesium/#/zh-CN/component/graphics/vc-graphics-wall
