### ISSUE TITLE
[Bug Report] 在北极画热力图的时候，出现了空洞

### ISSUE THREAD

**Issue by sakura41** [zouyaoji/vue-cesium#434]
### VueCesium version
3.2.2

### OS/Browsers version
Centos7.9/Edge

### Vue version
3.3.4

### Cesium version
1.108.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/bGBFFF无效

### Steps to reproduce
请访问【 http://test2.80s.gs 】查看北极的热力图状况。
数据的话，是在【 http://test2.80s.gs/data/ice.json 】

### What is Expected?
北极圈内应该是有热力点的，但实际上没有

### What is actually happening?
北极圈内应该是有热力点的，但实际上没有

**Comment by zouyaoji** [comment]
无解啊，热力图的思路是把数据换算到3857来弄的，3857就铺不满北极那儿。你可以试试cesiumlab mars3d 可能也是一样的。 建议你考虑用其他方式吧，换个插值方式绘制色斑图。

**Comment by sakura41** [comment]
哭。。。点太多，插值直接内存溢出了。大概有384x420个点位
这么大量的话，您能给个推荐么

**Comment by zouyaoji** [comment]
384*420没压力吧
