### ISSUE TITLE
[Bug Report] 2d，测量工具不显示距离和面积

### ISSUE THREAD

**Issue by weizheng1992** [zouyaoji/vue-cesium#437]
### VueCesium version
3.2.2

### OS/Browsers version
mac/google

### Vue version
3.3.4

### Cesium version
1.108.0

### Reproduction Link
https://codepen.io/weizheng1992/pen/XWomOgZ

### Steps to reproduce
点击测量工具

### What is Expected?
2d测量显示测量数据

### What is actually happening?
无

**Comment by zouyaoji** [comment]
源码文档未重现，npm安装的重现了。需要进一步跟踪，感谢反馈。

**Comment by zouyaoji** [comment]
![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/940eab48-40b0-4648-87f3-7d9f458bd700)


你好，这样即可。
![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/e340c48e-4774-4fe4-a6d4-eba5b2d7eb51)

**Comment by weizheng1992** [comment]
我加上了这个属性，在2d还是不行

**Comment by flywin8** [comment]
我也遇到同样的问题，加上这个属性也是不行
![image](https://github.com/user-attachments/assets/e2cfb30b-2618-4f79-9d0a-d18f926571b4)
