### ISSUE TITLE
[Bug Report] VcDrawings在超图cesium显示异常

### ISSUE THREAD

**Issue by kireiyume** [zouyaoji/vue-cesium#438]
### VueCesium version
3.2.2

### OS/Browsers version
win10

### Vue version
3.3.4

### Cesium version
1.67.0

### Reproduction Link
https://github.com/kireiyume/cesium-supermap-demo

### Steps to reproduce
git clone 项目，npm install 安装依赖然后，启动项目，
观察项目
内置的supermap cesium为最新正式版

### What is Expected?
在开启clampToGround为true的时候，能够在二维地图上显示边框，和渲染的面
在关闭的clampToGround时候，false时候，能显示正常的边框

### What is actually happening?
clampToGround为true，二维地图不显示绘制的边框和面；
clampToGround为false时候，虽然边框和面显示完整，但是边框的颜色锁死为绿色，我代码设置的为红色

**Comment by kireiyume** [comment]
clampToGround为true时候：
![clampToGround为true](https://s2.loli.net/2023/08/30/26SeLAGHinTPEfU.png)
clampToGround为false时候：
![clampToGround为false](https://s2.loli.net/2023/08/30/26SeLAGHinTPEfU.png)

**Comment by zouyaoji** [comment]
给你提了个pr，你看看吧

**Comment by kireiyume** [comment]
> 给你提了个pr，你看看吧

十分感谢

**Comment by kireiyume** [comment]
> 你好，解决了吗？准备关闭了哦 @kireiyume

解决了，十分感谢您，可以关闭了
