### ISSUE TITLE
Using a custom billboard image

### ISSUE THREAD

**Issue by boriskogan81** [zouyaoji/vue-cesium#44]
### 相关文档 URL

https://zouyaoji.top/vue-cesium/#/en/entity/vc-graphics-billboard

### 问题描述

I am trying to use a custom .png file for billboard graphics. This file is in my /src/assets folder as TentLogo.png. Passing the image this way: 
```billboard.image = '../assets/TentLogo.png';```
  in a component under /src/views does not work, meaning, it throws an error: 
```Error loading image for billboard: [object Event]```

Using a link to https://zouyaoji.top/vue-cesium/#/en/entity/vc-graphics-billboard as billboard.image works fine. 

Thoughts?

### 改进建议

```
Improve documentation to specify what sort of images do and don't work for graphics billboards.
```

**Comment by zouyaoji** [comment]
You should put image files into the project's public static directory.

**Comment by boriskogan81** [comment]
Thanks, got it working. 

Had to require the image and save it as a constant, like this:

```
    const tentLogo = require('../../public/img/TentLogo.png');
...
                    billboard.image = tentLogo;
```
