### ISSUE TITLE
[Bug Report] Not able to  display the globe and imagery

### ISSUE THREAD

**Issue by sachinsbgithub** [zouyaoji/vue-cesium#443]
### VueCesium version
3.2.2

### OS/Browsers version
all new broswer

### Vue version
3.3.4

### Cesium version
1.109.0

### Reproduction Link
https://codepen.io/sachinsbgithub/pen/NWebyzE

### Steps to reproduce
open the link and check console

### What is Expected?
Globe need to be loaded

### What is actually happening?
Globe is not loading, getting this error

Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().
    at a32529b6-da4f-4d8f-9f88-3f24aefaeec8:1:1   
 also i used vue cesium ,  getting the same issue in my live project .

**Comment by zouyaoji** [comment]
It is suspected to be a bug of cesium. Please follow this issue:

https://github.com/CesiumGS/cesium/issues/11505

**Comment by zouyaoji** [comment]
This appears to be a bug in the CDN version of Cesium. Until it's resolved by the official team, you can avoid this issue by placing Cesium in your project directory.

**Comment by sachinsbgithub** [comment]
Thank you for your response

**Comment by zouyaoji** [comment]
This issue has been fixed.
