### ISSUE TITLE
[Bug Report] 官网案例加载不出来了，控制台有报错

### ISSUE THREAD

**Issue by anihCevol** [zouyaoji/vue-cesium#444]
### VueCesium version
3.2.2

### OS/Browsers version
window

### Vue version
3.3.4

### Cesium version
1.109.0

### Reproduction Link
https://codepen.io/

### Steps to reproduce
https://vue-cesium.songluck.com/#/zh-CN/component/primitives/vc-primitive

### What is Expected?
https://vue-cesium.songluck.com/#/zh-CN/component/primitives/vc-primitive

### What is actually happening?
https://vue-cesium.songluck.com/#/zh-CN/component/primitives/vc-primitive

**Comment by zouyaoji** [comment]
重复了哈，请关注这个。
https://github.com/zouyaoji/vue-cesium/issues/443
