### ISSUE TITLE
[Bug Report] vc-primitive-tileset组件的ready事件触发过早，读取tileset.boundingSphere报错

### ISSUE THREAD

**Issue by 674948122** [zouyaoji/vue-cesium#446]
### VueCesium version
3.2.2

### OS/Browsers version
macos@12.6.6 (21G646)/chrome@116.0.5845.179

### Vue version
3.3.4

### Cesium version
1.109.0

### Reproduction Link
https://codepen.io/zouyaoji/pen/bGBOyJMo

### Steps to reproduce
vc-primitive-tileset组件的ready事件触发过早，读取tileset.boundingSphere报错

### What is Expected?
正常读取tileset.boundingSphere

### What is actually happening?
在ready事件里读取tileset.boundingSphere就会报错，延迟1秒读取正常了

**Comment by 674948122** [comment]
https://codepen.io/674948122/pen/mdamqax

**Comment by zouyaoji** [comment]
我看了一下，重现不了哈。
