### ISSUE TITLE
绘制点线面时可视化效果问题

### ISSUE THREAD

**Issue by GTXpeter** [zouyaoji/vue-cesium#45]
### 浏览器版本号

Google Chrome 已是最新版本 版本 79.0.3945.79（正式版本） （64 位）

### Vue 版本号

官网案例

### 组件库版本号

官网案例

### 现象描述

```
绘制的几何体边不能完整显示
```

### 完整异常信息

```
缺省
```

### 在线示例 / 仓库 URL

https://zouyaoji.top/vue-cesium/#/zh/tools/vc-drawing

### 复现用例

```
缺省
```

### 预期输出

```
缺省
```

### 实际输出

```
缺省
```

**Comment by GTXpeter** [comment]
![问题表现](https://user-images.githubusercontent.com/37895367/70961141-ec151800-20bb-11ea-89a1-f44afb0719ca.png)

**Comment by zouyaoji** [comment]
嗨，有个属性，depthTest设置为false即可，绘制默认是开启了深度测试的，量算没有开启，所以具体效果你可以看看量算的例子。
[https://zouyaoji.top/vue-cesium/#/zh/tools/vc-measuring](https://zouyaoji.top/vue-cesium/#/zh/tools/vc-measuring)

**Comment by AirWinger** [comment]
@zouyaoji 你好,在关闭深度测试的情况下，在测量绘制面时填充色显示不全
![image](https://user-images.githubusercontent.com/28389536/71248262-61e7e080-2355-11ea-9f09-24fa77d3e63d.png)

**Comment by AirWinger** [comment]
![1576837389](https://user-images.githubusercontent.com/28389536/71248478-e76b9080-2355-11ea-96a5-9a9cf00a9e93.png)

**Comment by zouyaoji** [comment]
@AirWinger 额，这个是实体对象的多边形，没做处理。。

**Comment by AirWinger** [comment]
@zouyaoji 这个好处理吗? 对cesium不太熟悉, 在网上看到直接添加实体多边形好像是没问题的?(非绘制实时数据绑定的情况下),如果是画完了之后再重新添加一个新的对应实体面来替换实时刻画的实体,会有问题吗?

**Comment by AirWinger** [comment]
@zouyaoji   好的，谢谢

**Comment by zouyaoji** [comment]
我的理解是，在关闭深度测试的情况下，很容易捕捉到地下的点，就出现这种情况了。如果想在地表上绘制，开启深度测试吧，然后把perPositionHeight设为false。
[cesium-dev](https://groups.google.com/forum/#!searchin/cesium-dev/PolygonGraphics|sort:date/cesium-dev/bB3aeTWqmgE/I2iURDlIEgAJ)

**Comment by zouyaoji** [comment]
加了个贴地绘制模式避免这种问题。
