### ISSUE TITLE
[Bug Report] VcViewer 销毁会清除window.cesium（创建多地球实例，销毁一个，其他地球实例都会报错）

### ISSUE THREAD

**Issue by 1298350966** [zouyaoji/vue-cesium#455]
### VueCesium version
3.2.2

### OS/Browsers version
谷歌 114.0.5735.199

### Vue version
3.3.4

### Cesium version
1.110.0

### Reproduction Link
https://github.com/zouyaoji/vue-cesium/blob/32f5265fca704a9b76d43c04dc9f48400e24fc15/packages/components/viewer/src/useViewer.ts#L781

### Steps to reproduce
<VcViewer>创建多个销毁
问题代码：
vue-cesium/packages/components/viewer/src/useViewer.ts
unload 方法
     globalThis.Cesium && (globalThis.Cesium = undefined!)
      globalThis.XbsjCesium && (globalThis.XbsjCesium = undefined)
      globalThis.XbsjEarth && (globalThis.XbsjEarth = undefined)
      globalThis.XE && (globalThis.XE = undefined)
      globalThis.mars3d && (globalThis.mars3d = undefined)
      globalThis.DC && (globalThis.DC = undefined)
      globalThis.DcCore && (globalThis.DcCore = undefined)
      globalConfig.value.__scriptPromise = undefined

### What is Expected?
无

### What is actually happening?
无

**Comment by zouyaoji** [comment]
这是默认行为，如果不想这也可以改变这个行为。vc-viewer组件上绑定 :removeCesiumScript="false"
![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/2c446533-20d0-46eb-bec0-cfc53e367dd1)
