### ISSUE TITLE
[Bug Report] 百度地图加载数据404

### ISSUE THREAD

**Issue by weizheng1992** [zouyaoji/vue-cesium#476]
### VueCesium version
3.2.4

### OS/Browsers version
mac

### Vue version
3.4.0-alpha.1

### Cesium version
1.111.0

### Reproduction Link
https://codepen.io/pen?editors=1111

### Steps to reproduce
直接使用百度地图

### What is Expected?
显示完整地图

### What is actually happening?
无

<img width="1379" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/10727313/cffb0ee9-9a97-436f-81a6-a2d48fe68269">

**Comment by weizheng1992** [comment]
引入后  修改热刷新会报错
<img width="939" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/10727313/c503acfd-cef0-409d-a00a-17e4e10cf419">

**Comment by zouyaoji** [comment]
vc-viewer组件上加一个:removeCesiumScript="false"试试

**Comment by weizheng1992** [comment]
https://codepen.io/spkie/pen/MWLXvaQ
2d 测量还是不行
:removeCesiumScript="false"
加上之后地图加载还是报错

**Comment by zouyaoji** [comment]
如果只是热更新有问题，刷新后正常的话先不着急，等我空了看看。

**Comment by zouyaoji** [comment]
你热更新改了些啥参数？我测试改mapStyle 热更新没问题呢。
