### ISSUE TITLE
[Bug Report] 2d 测量还是不行

### ISSUE THREAD

**Issue by weizheng1992** [zouyaoji/vue-cesium#482]
### VueCesium version
3.2.4

### OS/Browsers version
mac/google

### Vue version
3.4.0-alpha.3

### Cesium version
1.112.0

### Reproduction Link
https://codepen.io/spkie/pen/MWLXvaQ

### Steps to reproduce
直接使用  :distanceMeasurementOpts="{ disableDepthTest: true }" 不行

### What is Expected?
可用

### What is actually happening?
 :distanceMeasurementOpts="{ disableDepthTest: true }"

**Comment by zouyaoji** [comment]
拉很高的情况下拾取不到是吗？

**Comment by weizheng1992** [comment]
高低感觉都获取不到

**Comment by zouyaoji** [comment]
能出来的嘛，你给的例子只加了距离量算，其他的也要加。

![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/521228e1-f364-4ac9-bc06-05ffc0d1b554)

**Comment by weizheng1992** [comment]
其他的也要加？要加什么？
<img width="1513" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/10727313/376d4f7e-a146-4fa7-b745-44eaee15c7cf">

**Comment by zouyaoji** [comment]
只有距离量算是正常的 你给的例子

**Comment by weizheng1992** [comment]
其他的看了不知道哪个属性是
