### ISSUE TITLE
Initialization ignoring access token?

### ISSUE THREAD

**Issue by oddbytes** [zouyaoji/vue-cesium#5]
Hi!

i'm initializating vue-cesium like this

```
Vue.use(VueCesium, {
  accessToken: "access_tokeen",
  cesiumPath: "https://unpkg.com/cesium/Build/Cesium/Cesium.js",
});
```

But the requests to the endpoint are still using the default hard-coded access token. 

Using npm package 0.0.17.

Thanks,

Jesus

**Comment by oddbytes** [comment]
Hi!

I can confirm that the 0.0.17 npm package  contains the 0.0.16 production build, rebuilding the code works correctly.

Regards,

Jesus

**Comment by zouyaoji** [comment]
Received, I will solve this problem today, thank you.

**Comment by zouyaoji** [comment]
@oddbytes   fixed.
