### ISSUE TITLE
cesuim新版好像没有createTileMapServiceImageryProvider这个方法了

### ISSUE THREAD

**Issue by cehui0303** [zouyaoji/vue-cesium#50]
cesuim新版好像没有createTileMapServiceImageryProvider这个方法了, cesiumPath: 'https://unpkg.com/cesium/Build/Cesium/Cesium.js' 默认调用最新的js因此出现ncaught (in promise) TypeError: e.createTileMapServiceImageryProvider is not a function的错误

**Comment by zouyaoji** [comment]
hi @cehui0303，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！
