### ISSUE TITLE
Allow `stackblitz` as option to reproduce issue

### ISSUE THREAD

**Issue by pilcstp** [zouyaoji/vue-cesium#505]
[stackblitz](https://stackblitz.com/) does not require signing in and offers many common templates. People have issue may use vue3+js/ts+vite/webpack or something else, so it's much more flexible to reproduce an issue. Currently it seems the issue template has limited rules for reproduction link.

**Comment by zouyaoji** [comment]
Due to the version update, the original issue template is indeed no longer working. I am going to fix it and add the stackblitz option.

**Comment by zouyaoji** [comment]
added in https://zouyaoji.top/issue-generator/#/en-US
