### ISSUE TITLE
Import `VcViewer` cannot be resolved

### ISSUE THREAD

**Issue by pilcstp** [zouyaoji/vue-cesium#506]
## Reproduction

See: https://stackblitz.com/edit/vitejs-vite-yw7wvf?file=src%2FApp.vue&view=editor

- Run `vue-tsc` shows the error

**Comment by zouyaoji** [comment]
hi @pilcstp，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/9289e8a7-9090-454d-ae1a-dca6d17e3222)
![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/c579964e-2cfd-406b-9be4-ccb5e4a88f44)
