### ISSUE TITLE
怎么样能让地球隐藏一下

### ISSUE THREAD

**Issue by wh123660** [zouyaoji/vue-cesium#51]
我们的需求是地球上显示一个模型，另外有个按钮，可以把地球隐藏或显示，但是现在我设置的viewer.scene.globe.show = false,设置完之后地球是消失了， 但是会出现一个白色光圈，像是大气层一样的，怎么设置都隐藏不了，也试过cesium里面的把大气层去掉，但是好像和这个没关系，设置了不管用，就下面图片上的这样
![image](https://user-images.githubusercontent.com/20349017/74999057-85362580-5495-11ea-8859-e8bd2bf33275.png)

**Comment by zouyaoji** [comment]
hi @wh123660，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！
