### ISSUE TITLE
pnpm i安装卡在electron

### ISSUE THREAD

**Issue by lienahu9** [zouyaoji/vue-cesium#513]
报错内容：Failed in 786ms at \node_modules\.pnpm\electron@11.5.0\node_modules\electron
 ELIFECYCLE  Command failed with exit code 1.
试过切换淘宝镜像，没用，多次删包清缓存重安装也没用。。。

**Comment by zouyaoji** [comment]
hi @lienahu9，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
