### ISSUE TITLE
How to update the data for BillboardCollection at regular intervals without flickering effect?

### ISSUE THREAD

**Issue by philiptran** [zouyaoji/vue-cesium#53]
Hi @zouyaoji,

First of all, thank you for the great library. I'm trying out the component for `BillboardCollection` by making changes to the `vc-collection-primitive-billboard.md`. The billboard collection works great for static collection of billboards.

I have a requirement to update the collection of billboards (adding, removing the items or replace the whole collection) at an interval of every X seconds. I try to test this behavior using the attached version of `vc-collection-primitive-billboard.md` as follow. 

1) Create a testUpdate() method that is called every 5 seconds to update the `changingBillboards` data
2) Cesium viewer updates the `changingBillboards` correctly with **some flickering effect**

**Expected Result:**
1. What is the correct way to update the `changingBillboards` data so that Cesium viewer only updates the `delta` changes in the map and reduces the flickering effect? Assume that I can establish the unique ID for each item in the `changingBillboards` data.

I have attached my version of `vc-collection-primitive-billboard.md` for your quick reference.

Thank you.

[vc-collection-primitive-billboard.md.TXT](https://github.com/zouyaoji/vue-cesium/files/4362588/vc-collection-primitive-billboard.md.TXT)

**Comment by zouyaoji** [comment]
hi @philiptran，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！

**Comment by zouyaoji** [comment]
Not currently, because changing the billboards array vc-collection-primitive-billboard will overload and cause flicker.

If the billboard's id hasn't changed, I can dynamically change its position in the component by listening for billboards changes, instead of removing and adding. It may solve the problem, but assigning a new array directly should not work.
