### ISSUE TITLE
[Bug Report] 实体VcEntity如何去处默认的绿色框框

### ISSUE THREAD

**Issue by Zhang-DaLei** [zouyaoji/vue-cesium#536]
### VueCesium version
3.2.6

### OS/Browsers version
macOS/Chrom122.0.6261.129

### Vue version
3.4.21

### Cesium version
1.115.0

### Reproduction Link
https://codepen.io/pen

### Steps to reproduce
点击实体VcEntity地图会出现绿色的框

### What is Expected?
点击实体VcEntity地图去处绿色的框

### What is actually happening?
点击实体VcEntity地图会出现绿色的框
<img width="720" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/23338914/f0439efb-54e2-475f-acb0-4a6eec8057a1">

**Comment by zouyaoji** [comment]
vc-viewer上绑定:selectionIndicator="false"
