### ISSUE TITLE
添加鹰眼视图功能

### ISSUE THREAD

**Issue by loyalove** [zouyaoji/vue-cesium#54]
### 在线示例 URL

http://liubf.com/LBF_Earth_SoftWare/#/

### 功能描述

```
添加鹰眼视图功能，便于快速定位到目标位置
```

### 用法示例

```
示例URl中右下角所示
```

**Comment by zouyaoji** [comment]
你好，这个我考虑一下啊，后面测试一下看看，鹰眼地图得引入leafletjs，可能让vue-cesium会增大很大。我评估一下是在项目中自己做还是说封成组件吧。那个定位api也是，目前其实已经有一个定位的了，用的是浏览器提供的api，但国内谷歌被墙了，火狐或者微软的浏览器可以使用。 当时也是考虑到要引入其他比较庞大的js库没弄，需求我都考虑一下哈

鹰眼可以参考这个做一个
https://www.jianshu.com/p/e6f3d171a2d1
定位着急的话，可以先在用高德或者百度api在你的项目业务中实现一下。

**Comment by zouyaoji** [comment]
准备结合 leaflet 搞一个，单独引入。

**Comment by zouyaoji** [comment]
@loyalove 已经增加 [vc-map-overview](https://zouyaoji.top/vue-cesium/#/zh/control/vc-map-overview).  2.1.6+版本有此组件。
