### ISSUE TITLE
[Bug Report] 量算组件放在pop层中行为异常

### ISSUE THREAD

**Issue by MangMax** [zouyaoji/vue-cesium#548]
### VueCesium version
3.2.7

### OS/Browsers version
win11

### Vue version
3.4.24

### Cesium version
1.90.0

### Reproduction Link
https://codepen.io/1061875478/pen/yLrZOZO

### Steps to reproduce
将量算功能按钮自定义在pop组件中，完成量算绘制后重新点击pop触发按钮
![PixPin_2024-04-24_09-49-00](https://github.com/zouyaoji/vue-cesium/assets/68525017/83b34e17-6586-4b77-bad6-9c14d273a004)

### What is Expected?
和正常绘制一样，不会自动消失

### What is actually happening?
量算绘制消失，此现象出现在el plus组件库中，在arco desing vue中点击任何地图以外其他对象均会消失，猜测可能是量算组件跟随pop组件一起销毁了或者是重载了

**Comment by zouyaoji** [comment]
使用问题哈。

![image](https://github.com/zouyaoji/vue-cesium/assets/24430116/f608f4c7-bf93-4aa4-bb9b-7191b0eb437f)

**Comment by MangMax** [comment]
我这个例子举得不对，明天我再试试能不能复现，实际项目中确实是有这个问题存在
