### ISSUE TITLE
[Bug Report] 量算组件放在pop层中行为异常

### ISSUE THREAD

**Issue by MangMax** [zouyaoji/vue-cesium#549]
### VueCesium version
3.2.7

### OS/Browsers version
win11

### Vue version
3.4.25

### Cesium version
1.116.0

### Reproduction Link
https://codepen.io/1061875478/pen/yLrZOZO
![recording](https://github.com/zouyaoji/vue-cesium/assets/68525017/7e65c166-31bd-4b67-9cf8-df22a1325a6c)

### Steps to reproduce
将量算组件放入popover中，具体想要实现的效果是一个图标，鼠标悬浮有文字提示，点击会出现量算功能图标，每个量算功能鼠标悬浮也有文字提示

### What is Expected?
绘制完成后，点击其他元素，绘制的结果没影响

### What is actually happening?
绘制完成后，点击其他元素或者pop消失，绘制结果消失

**Comment by zouyaoji** [comment]
你不要把vc-measurements放n-popover中呗，很明显点击其他区域n-popover被销毁了，如果vc-measurements是n-popover的子组件也会跟着销毁了。

解决办法就是把vc-measurements放到外面去，然后 #body 插槽啥也不放。n-popover下面你另外弄按钮，在按钮的事件去，然后用vc-measurements的模板引用去调用相关量算方法咯。

**Comment by MangMax** [comment]
ok，可以了，谢谢
