### ISSUE TITLE
[Bug Report] 加载出来的地球放大很糊

### ISSUE THREAD

**Issue by bigbignono** [zouyaoji/vue-cesium#554]
<img width="1150" alt="WechatIMG134" src="https://github.com/zouyaoji/vue-cesium/assets/118282923/b8e54ec3-4852-4c41-91fc-16945d2563c5">

### VueCesium version
3.2.7

### OS/Browsers version
chorme

### Vue version
3.4.20

### Cesium version
1.117.0

### Reproduction Link
https://codepen.io/bigbignono/pen/MWdggYp

### Steps to reproduce
本地的效果和示意的链接是一样的，放大之后地图非常糊

### What is Expected?
放大后能正常显示地球影像

### What is actually happening?
很糊，几乎看不清

**Comment by bigbignono** [comment]
vc-viewer 放大地球后没有去请求资源，正常原始html的引入方式放大后会去请求资源

**Comment by zouyaoji** [comment]
你这都没加底图得嘛，自己加一个就好了哈。

https://zouyaoji.top/vue-cesium/#/zh-CN/component/providers/vc-imagery-provider-tianditu
