### ISSUE TITLE
How do I make the initial load time faster? 

### ISSUE THREAD

**Issue by boriskogan81** [zouyaoji/vue-cesium#56]
### 相关文档 URL

https://github.com/zouyaoji/vue-cesium

### 问题描述

```
The initial load of map imagery takes approximately 30 seconds. How can I expedite this? Can I load a lower resolution map as a placeholder? 

My component looks like this:

```
        <vc-viewer :requestRenderMode="true"
                   :infoBox="false"
                   :geocoder="geocoder"
                   :terrainExaggeration="100"
                   @ready="ready"
                   :camera="camera"
                   @selectedEntityChanged="selectedEntityChanged"
                   @moveEnd="onMoveEnd">
            
            <vc-entity v-if="billboards.length > 0" v-for="billboard in billboards"
                       :ref="billboard.id"
                       :position="billboard.position"
                       :billboard="billboard"
                       :key="billboard.id"
                       :id="billboard.id.toString()"></vc-entity>
            
            <vc-layer-imagery :alpha="alpha" :brightness="brightness" :contrast="contrast">
                <vc-provider-imagery-bingmaps :url="url" :bmKey="bmKey" :mapStyle="mapStyle"/>
            </vc-layer-imagery>
        </vc-viewer>
```
```

### 改进建议

```
Document a way to make the map imagery load faster initially.
```

**Comment by zouyaoji** [comment]
Do you mean it takes 30 seconds to load the viewer, or 30 seconds for the bingmaps layer?

In my [example](https://zouyaoji.top/vue-cesium/#/zh/imagery/vc-provider-imagery-bingmaps), bingmaps load very quickly. If you are bingmaps load slowly, maybe the network between you and the bingmaps map service is not good.

**Comment by boriskogan81** [comment]
I mean that it takes a long time for the imagery layer to load, and the first time it doesn't load properly. You can see what I'm talking about in this screencast: https://youtu.be/AtCB0u0XYEE

It seems like this may be a Cesium issue as well.

**Comment by zouyaoji** [comment]
I think it may be too slow to load Cesium.js. You can try to put cesiumjs on your server and load it locally.

```js
Vue.use(VueCesium, {
  cesiumPath: /YouerPath/Cesium/Cesium.js
  accessToken: 'XXXX'
})
```

**Comment by boriskogan81** [comment]
Wow, I had no idea Cesium weighed 55 MB!

Is there any sort of light version or some other workaround you could
recommend?

Sincerely,

Baruch

**Comment by zouyaoji** [comment]
You only need the files in the "Cesium-1.64 \ Build \ Cesium" directory.

**Comment by boriskogan81** [comment]
I placed the Cesium build folder into my /staticfolder, and passed it to
Vue in my main file like this:
```
Vue.use(VueCesium, {
    cesiumPath: '/static/Cesium/Cesium.js',
    accessToken:
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkOGM5ZTQwZS1hMDA2LTQ3MjgtOTQ5ZC03ZjU5ZTBkZTRiMjQiLCJpZCI6NzQwMSwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTU3NTQ3ODUyOH0.w9ZktD2If7v4lwzIj2jk5g0hlYBqal6ko9B9QybBXb4'
});
```
This fails with

```
index.js?22a4:890 Uncaught ReferenceError: Cesium is not defined
    at HTMLScriptElement.$script.onload
```

What am I missing?

Sincerely,

Baruch

**Comment by zouyaoji** [comment]
Please make sure that your cesium.js can be directly accessed in the browser address bar, like this:
![image](https://user-images.githubusercontent.com/24430116/78732363-104f7a00-7975-11ea-9f70-b9cd951bfd01.png)

**Comment by boriskogan81** [comment]
I can not. What should I set up to make the statics folder available?

**Comment by zouyaoji** [comment]
Please refer to the vue scaffolding project.

**Comment by boriskogan81** [comment]
Ah, ok-the default Vue CLI 3 sets it up so that you need to put Cesium in the /public folder, and then can pass it in Vue registration like this:

`cesiumPath: '/Cesium/Cesium.js',`

My question is whether I have to include the Cesium/Assets, /ThirdParty, /Widgets and /Workers folders.

**Comment by zouyaoji** [comment]
Just need to include Cesium.js.
