### ISSUE TITLE
[Bug Report] VcImageryProviderTianditu - maximumLevel invalid

### ISSUE THREAD

**Issue by FrozenJun** [zouyaoji/vue-cesium#582]
### VueCesium version
3.2.8

### OS/Browsers version
windows 11 / chrome 118

### Vue version
3.4.4

### Cesium version
1.119.0

### Reproduction Link
https://codepen.io/llisacxo-the-vuer/pen/qBzdNQN

### Steps to reproduce
点击链接，摄像头移动至中国境内贴地，会出现白色色块

### What is Expected?
摄像头很低时，最大的请求level一直是18

### What is actually happening?
VcImageryProviderTianditu 设置 maximumLevel=18 ，摄像头很低时，请求level会出现 undefined和19/20。但高德的组件实测不会有这个问题

**Comment by zouyaoji** [comment]
设置成17哈
