### ISSUE TITLE
[Feature Request] 我想在项目单独使用量算组件，之前的结构不好改了，可以单独使用吗？

### ISSUE THREAD

**Issue by xiaobaiQJ** [zouyaoji/vue-cesium#585]
### Existing Component
否

### Component Name
量算

### Description
我现有的项目不太方便全套更换成vue-cesium，我只想用量算这一个组件，可是他好像必须和viewer那个组件搭配使用

**Comment by zouyaoji** [comment]
不行哈，只有自己参考源码搞一下了。
