### ISSUE TITLE
vue3+viet5 引入运行项目 特别的卡  电脑会卡崩溃

### ISSUE THREAD

**Issue by IKE1001** [zouyaoji/vue-cesium#587]
电脑配置：
mac：版本 14.0
存储空间：512G
内存：8G
chrom：版本 127.0.6533.73

**Comment by zouyaoji** [comment]
hi @IKE1001，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
