### ISSUE TITLE
用最新的0.0.18版本调用cesium的地形服务会出错

### ISSUE THREAD

**Issue by GPBOB** [zouyaoji/vue-cesium#6]
用cesium的地形服务：
https://api.cesium.com/v1/assets/2/endpoint?access_token=ey... 会报404，
用我自己的地形服务，控制台会出现这一行字：
An error occurred in "x": An error occurred while accessing https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles/layer.json.
这是什么问题

**Comment by zouyaoji** [comment]
@GPBOB 你用在线的地形要去 [CesiumIon](https://cesium.com/ion/) 注册一个账号，分配一个`AccessToken`才可以的。

**Comment by zouyaoji** [comment]
如果没有后续问题准备关闭issue了哦。
