### ISSUE TITLE
Using a static image for billboards needs to be documented more clearly

### ISSUE THREAD

**Issue by boriskogan81** [zouyaoji/vue-cesium#60]
### 相关文档 URL

https://zouyaoji.top/vue-cesium/#/en/entity/vc-graphics-billboard

### 问题描述

```
I am deploying my app, using Vue Cesium, to Heroku, and have a .png in my static assets folder which I am trying to use for a billboard, like this: 
```
                this.billboards = this.$store.state.communities.map(community => {
                    return {
                        position: {lng: community.coordinates.x, lat: community.coordinates.y},
                        image: '/img/TentLogo.png',
                        scale: 0.1,
                        id: community.id
                    };
                })
```

I can see the .png file if I navigate to baseAddress/img/TentLogo.png, but the billboards are not showing up on the map. 

Previously, this worked ok locally, so I suspect it may have something to do with the environment, but am not sure how to troubleshoot it. 

Could I request a bit more detail on how linking static images in billboards works? 
```

### 改进建议

```
A bit more documentation on this issue.
```

**Comment by zouyaoji** [comment]
Please make sure that the URL of the picture can be successfully accessed after entering it in the address bar of the browser. Then try to write the entire path of this url to the image attribute.

**Comment by boriskogan81** [comment]
The picture URL can be accessed (
https://itribe-frontend.herokuapp.com/img/TentLogo.png).

Setting the image attribute to this URL does not fix the problem.

Sincerely,

Baruch

**Comment by zouyaoji** [comment]
I tried it. This is because your background service does not allow cross-domain. The error message output from the browser console can be clearly seen. You can let the background service allow cross-domain, or front-end proxy to solve this problem.
![image](https://user-images.githubusercontent.com/24430116/82718474-4d798c80-9cd5-11ea-8b43-1c53b6ec26c7.png)

**Comment by boriskogan81** [comment]
I'm running the application itself at the same domain,
http://itribe-frontend.herokuapp.com.

**Comment by boriskogan81** [comment]
I should also point out that migrating from 2.0.0 to 2.1.3 breaks the vc-layer imagery-an error is thrown regarding inability to find the viewModel. This should probably also be documented. This is a breaking change.

**Comment by zouyaoji** [comment]
The next version will solve this problem.

**Comment by boriskogan81** [comment]
Great, looking forward to it.

I also notice that upgrading to the latest version has caused the Bingmaps
imagery layer to stop working.

**Comment by zouyaoji** [comment]
I don't have this problem here. Please provide a reproduction method or example. It is recommended to create a new issue to discuss other issues.

**Comment by boriskogan81** [comment]
It works with the latest version-thank you!
