### ISSUE TITLE
[Bug Report] 在多个页面使用vue-cesium组件，然后快速切换各个页面会报错

### ISSUE THREAD

**Issue by lushfe** [zouyaoji/vue-cesium#601]
### VueCesium version
3.2.8

### OS/Browsers version
chrome最新版

### Vue version
3.5.5

### Cesium version
1.121.1

### Steps to reproduce
在多个路由中使用vue-cesium，快速切换页面，控制台会有很多报错信息

### What is Expected?
清除报错信息

### What is actually happening?
清除报错信息

**Comment by zouyaoji** [comment]
需要反复切换多个vc-viewer组件初始化的球，需要把removeCesiumScript设置为false。
