### ISSUE TITLE
关于该框架应用外部资源问题

### ISSUE THREAD

**Issue by ZKaiCode** [zouyaoji/vue-cesium#61]
该框架基于Ceiusm 封装实现了大量的vue 基础组件，想知道改封装思路是结合了Cesium官方和超图的Cesium WebGL 进行构建实现的吗？

**Comment by zouyaoji** [comment]
hi @ZKaiCode，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/issues) page, it will be closed directly, thank you!
