### ISSUE TITLE
关于vue-cesium 封装思路的学习请教

### ISSUE THREAD

**Issue by ZKaiCode** [zouyaoji/vue-cesium#62]
您好 我是一名GIS开发人 关于看了您封装的vue-cesium 源码后有以下两个疑问希望能得到您的解答，感谢
 1、关于vue-cesium的封装是否应用来自多源开发平台的基础参考、cesium和基于cesium的超图cesium webgl 开发平台
2、有关封装的思想比如像entity 实体组件封装思路代码应用引入该如何向内部查询参考学习
 
很希望能得到来自您的解答和收到您的邮件；本人邮箱1830101972@qq.com

**Comment by zouyaoji** [comment]
hi @ZKaiCode，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/issues) page, it will be closed directly, thank you!
