### ISSUE TITLE
不适用vc-entity标签（封装好的标签），通过viewer原生添加实体？？

### ISSUE THREAD

**Issue by Posiedon-WH** [zouyaoji/vue-cesium#64]
我想通过调用cesium自己的api来创建实体，而不是通过封装好的vc-entity
` ready(cesiumInstance){
                let {Cesium,viewer}=cesiumInstance;
                var p1 = viewer.entities.add({
                    ploygon:{
                        hierarchy : Cesium.Cartesian3.fromDegreesArray([
                            -109.080842,45.002073,
                            -105.91517,45.002073,
                            -104.058488,44.996596,
                            -104.053011,43.002989,
                            -104.053011,41.003906,
                            -105.728954,40.998429,
                            -107.919731,41.003906,
                            -109.04798,40.998429,
                            -111.047063,40.998429,
                            -111.047063,42.000709,
                            -111.047063,44.476286,
                            -111.05254,45.002073]),
                        height : 0,
                        material : Cesium.Color.RED.withAlpha(0.5),
                        outline : true,
                        outlineColor : Cesium.Color.RED
                    }
                });
                viewer.zoomTo(p1)
            }`

**Comment by zouyaoji** [comment]
hi @Posiedon-WH，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/issues) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
是可以的哈。
