### ISSUE TITLE
heatmapjs 和echarts冲突

### ISSUE THREAD

**Issue by DreamapleHT** [zouyaoji/vue-cesium#642]
heatmapjs 和echarts冲突，导致项目打包后报错 XXXX  is not a funtion，开发的时候不会报错

**Comment by zouyaoji** [comment]
hi @DreamapleHT，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
