### ISSUE TITLE
布告板图元heightReference属性值设置为1时报错

### ISSUE THREAD

**Issue by yshch3** [zouyaoji/vue-cesium#65]
![image](https://user-images.githubusercontent.com/63084333/83709018-3715ee00-a650-11ea-8e0a-1047be871b8a.png)

**Comment by zouyaoji** [comment]
你好，布告板图元heightReference属性值设置为1时，需要给布告板图元集合`vc-collection-primitive-billboard`设置scene属性，才能正常渲染。
![image](https://user-images.githubusercontent.com/24430116/83828000-36de2700-a712-11ea-9349-7ee5c2b05e6c.png)
