### ISSUE TITLE
由infoBox设置成false引发的错误

### ISSUE THREAD

**Issue by heyonggis** [zouyaoji/vue-cesium#69]
<vc-viewer :infoBox="false">
...
</vc-viewer>
结果加载不出来地球
发现是registerEvents函数出错,修改错了就好了

 registerEvents: function registerEvents(flag) {
      var _this4 = this;

      var viewer = this.viewer;
      bindEvents.call(this, viewer, undefined, flag);
      Events['viewer-property-events'].forEach(function (eventName) {
    //------------添加---------------------
      if(isArray(eventName.name)){
          if(viewer[eventName.name[0]] === undefined){
            return true;
          }
        }
 //------------添加---------------------

        var instance = isArray(eventName.name) ? viewer[eventName.name[0]][eventName.name[1]] : viewer[eventName.name];
        instance && bindEvents.call(_this4, instance, eventName.events, flag);
      });
      var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
      Events['viewer-mouse-events'].forEach(function (eventName) {
        var listener = _this4.$listeners[eventName];
        var methodName = flag ? 'setInputAction' : 'removeInputAction';
        listener && handler[methodName](listener.fns, Cesium.ScreenSpaceEventType[eventName]);
      });
    },

**Comment by zouyaoji** [comment]
hi @heyonggis，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
