### ISSUE TITLE
Layer's base maps

### ISSUE THREAD

**Issue by alipajand** [zouyaoji/vue-cesium#7]
Hi, thank you for your library.
I want to ask you how we can change the base maps from cesium? (Base map means it should always being under the all other layers)
Do you have any idea to help me?

**Comment by zouyaoji** [comment]
Hello,
You can reference my [demo](https://zouyaoji.top/vue-cesium/#/en/imageryLayers/wmts-imagery-provider).
```js
layerAdded () {
  if (this.$refs.layerText.imageryLayer) {
    const {viewer} = this.cesiumInstance
    viewer.imageryLayers.raiseToTop(this.$refs.layerText.imageryLayer)
  }
}
```

but you shoud use the `lowerToBottom `  api.
