### ISSUE TITLE
出现“Uncaught SyntaxError: Unexpected token import”错误是什么原因呢？

### ISSUE THREAD

**Issue by mayi8986** [zouyaoji/vue-cesium#70]
Uncaught SyntaxError: Unexpected token import
![image](https://user-images.githubusercontent.com/38170113/85196442-d6073f00-b30c-11ea-884c-0f4a5d5e8c3e.png)

**Comment by zouyaoji** [comment]
方便提交复现工程吗?

**Comment by mayi8986** [comment]
我只是创建了个Electron项目，只是引用了下vue-cesium，还没写什么代码!









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zouyaoji"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月21日(星期天) 晚上10:27
收件人:&nbsp;"zouyaoji/vue-cesium"<vue-cesium@noreply.github.com&gt;;
抄送:&nbsp;"不系舟"<178782933@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zouyaoji/vue-cesium] 出现“Uncaught SyntaxError: Unexpected token import”错误是什么原因呢？ (#70)





 
方便提交复现工程吗?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

cesiumtest.zip (130.19M, 2020年07月21日 22:55 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72353438b4c1bdc6e4379c321034531e0857515e000055531c0c0c0050195508000019595255591c50060c5c070c55550400070d363a615254465d4d5b400442451b4e5146345c&code=154864a1

**Comment by zouyaoji** [comment]
@mayi8986 npm安装后  npm run dev跑不起来呢 报错 是还要装什么环境吗？

**Comment by zouyaoji** [comment]
@mayi8986 
我刚测了一下，没发现问题。

![image](https://user-images.githubusercontent.com/24430116/124610786-5f9b9780-dea3-11eb-9586-2c0828607fb3.png)

**Comment by zouyaoji** [comment]
https://github.com/zouyaoji/vue-cesium-electron-vite-starter

**Comment by Ian-Wangyk** [comment]
VM4977:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)为什么我是用官网案例的路线跟踪引用JSON文件报这个错误

**Comment by zouyaoji** [comment]
如果球都出不来的话，检查一下cesiumjs的地址是不是没写对
