### ISSUE TITLE
gl_FragDepthEXT undclared identifier

### ISSUE THREAD

**Issue by yqh708** [zouyaoji/vue-cesium#72]
你好，我想问一下，风向图在移动端展示时候，会报gl_FragDepthEXT undclared identifier错误，这个要怎么解决呢？

**Comment by zouyaoji** [comment]
你好，原作者这儿有个解释：
[https://github.com/RaymanNg/3D-Wind-Field/issues/19](https://github.com/RaymanNg/3D-Wind-Field/issues/19)

说是很多手机不支持 WebGL的EXT_frag_depth特性。
如果你擅长glsl的话可以尝试参考这个改一改：
[https://github.com/RaymanNg/3D-Wind-Field/issues/19#issuecomment-526209436](https://github.com/RaymanNg/3D-Wind-Field/issues/19#issuecomment-526209436)

**Comment by yqh708** [comment]
谢谢您的回复，我只是一个初学的giser,这是没有本事改了。实在不行就用canvas展示了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zouyaoji"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 上午9:25
收件人: "zouyaoji/vue-cesium"<vue-cesium@noreply.github.com&gt;; 
抄送: "sky"<522346365@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zouyaoji/vue-cesium] gl_FragDepthEXT undclared identifier (#72)





 
你好，原作者这儿有个解释：
 RaymanNg/3D-Wind-Field#19
 
说是很多手机不支持 WebGL的EXT_frag_depth特性。
 如果你擅长glsl的话可以尝试参考这个改一改：
 RaymanNg/3D-Wind-Field#19 (comment)

**Comment by zouyaoji** [comment]
好的，这个glsl我也涉猎不深，也改不了，不好意思。不过我问了之前提问题的人，如果他解决了愿意分享的话我会在此再回复。

**Comment by yqh708** [comment]
谢谢您

**Comment by quater23** [comment]
webgl2环境下 EXT_frag_depth 已经是标准特性了，直接使用即可，注意修改：
```
gl_FragDepthEXT => gl_FragDepth
```
