### ISSUE TITLE
vue-cesium组件库里面的组件可以单独使用吗？

### ISSUE THREAD

**Issue by mdxiaohu** [zouyaoji/vue-cesium#77]
例如：
我在Vue工程里面，
使用官方的Dome创建了一个三维地图，
现在我只想使用vue-cesium里面的测量组件，
我可以将创建的Viewer和Cesium传入到测量组件,
然后就可以使用这个组件的功能吗？

我尝试下载了源码，里面层层封装，
好像要使用vc-viewer创建的地图，
才可以使用组件库里面的相关组件，具体我不是很了解。

**Comment by zouyaoji** [comment]
hi @mdxiaohu，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
是的，至少要用vc-viewer才行哈。通过vc-viewer创建的cesium实例您也是比较方便管理的。能获取到viewer
