### ISSUE TITLE
[BUG Feedback] Heatmap might use wrong projection

### ISSUE THREAD

**Issue by NoPodi** [zouyaoji/vue-cesium#78]
### Browser
Edge (Chromium)

### Vue Version
1.73.0

### VueCesium Version
2.1.6

### Problem Description
When projecting a heatmap over the whole globe the WebMercatorProjection renders an unexprected result.

Changing the projection to GeographicProjection renders the expected result.

### Online example / github URL
[https://github.com/NoPodi/heatmap-issue](https://github.com/NoPodi/heatmap-issue)

### Expected result
Latitude values should display with equal distance around the globe.

### Actual result
Latitude values get spread out approaching the poles.

**Comment by zouyaoji** [comment]
Hi I haven't used it in the 2D scene, can you provide the code for me to test it?
