### ISSUE TITLE
Layers ordering/sorting

### ISSUE THREAD

**Issue by alipajand** [zouyaoji/vue-cesium#8]
Hi
I have an array of imagery-layers and I want to show them based on my array orders but when I hide a layer the show it, it appears over of all my previous layers. how should I handle this?
I want to handle my base map layers and other imagery layers but all layer based on when they created not my own ordering!

**Comment by alipajand** [comment]
@zouyaoji thanks to help me if you have any idea

**Comment by zouyaoji** [comment]
@alipajand 
Hello，You can try using v-show instead of v-if command directive.

**Comment by zouyaoji** [comment]
Please let me know if it helps you.
