### ISSUE TITLE
vue3 vite vue-cesium

### ISSUE THREAD

**Issue by vinnitu** [zouyaoji/vue-cesium#82]
Hello from Ukraine!

Do you plan vue3 version of your components?

**Comment by zouyaoji** [comment]
hi @vinnitu，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
Yes, the plan is to start at the end of the year.

**Comment by zouyaoji** [comment]
@vinnitu 

It's coming...

https://zouyaoji.top/vue-cesium/#/en-US/component/installation
