### ISSUE TITLE
如何集成天地图提供的三维地形服务

### ISSUE THREAD

**Issue by lyh200731** [zouyaoji/vue-cesium#84]
天地图官方提供的2种方式测试了都不成功

**Comment by zouyaoji** [comment]
hi @lyh200731，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
