### ISSUE TITLE
您好 请问我首次加载地图特别慢 怎样才能优化呢？

### ISSUE THREAD

**Issue by kamiaki** [zouyaoji/vue-cesium#86]
您好 请问我首次加载地图特别慢 怎样才能优化呢？感觉不是瓦片加载的慢，就是3d地球出来的慢

**Comment by zouyaoji** [comment]
hi @kamiaki，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
