### ISSUE TITLE
控件-导航罗盘 中相机高度 不会随着缩放和鼠标移动 即时刷新

### ISSUE THREAD

**Issue by 2210469432** [zouyaoji/vue-cesium#88]
### 浏览器版本号

chrome 83.0.4103.61 64位

### Vue 版本号

2.5.2

### 组件库版本号

2.0.5

### 现象描述

```
控件-导航罗盘 中相机高度 不会随着缩放和鼠标移动 即时刷新
```

### 完整异常信息

```
控件-导航罗盘 中相机高度 不会随着缩放和鼠标移动 即时刷新
```

### 在线示例 / 仓库 URL

https://zouyaoji.top/vue-cesium/#/zh/control/vc-navigation

### 复现代码

```
<vc-navigation :options="options"></vc-navigation>
```

### 预期输出

```
缩放时 相机高度值 会 即时刷新
```

### 实际输出

```
缩放时 相机高度值 不能 即时刷新
```

**Comment by zouyaoji** [comment]
鼠标移动相机高度是不会变的，因为相机没改变。
但缩放中轮是变了的呀~
这个在线demo你那也没变?
[https://zouyaoji.top/vue-cesium/#/zh/control/vc-navigation](https://zouyaoji.top/vue-cesium/#/zh/control/vc-navigation)

**Comment by zouyaoji** [comment]
未复现，也没有进一步反馈，关闭了。
