### ISSUE TITLE
更新模型如何调用

### ISSUE THREAD

**Issue by mercury20160104** [zouyaoji/vue-cesium#90]
加载模型时<vc-primitive-tileset :url="modelUrl" @readyPromise="readyPromise"></vc-primitive-tileset>
如何要对模型更新该如何调用呢？

**Comment by zouyaoji** [comment]
hi @mercury20160104，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!
