### ISSUE TITLE
知乎上有人说不要把viewer挂到this上，会严重影响性能，求解释

### ISSUE THREAD

**Issue by 531431988** [zouyaoji/vue-cesium#94]

**Comment by zouyaoji** [comment]
hi @531431988，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!

**Comment by 531431988** [comment]
https://zhuanlan.zhihu.com/p/157721176?from_voters_page=true
