### ISSUE TITLE
DocPreview.vue能解释下啥意思

### ISSUE THREAD

**Issue by liyihongcug** [zouyaoji/vue-cesium#96]
问题
1 引用的什么库
2 为何都没<> 之类的括号

<template lang="pug">
md-whiteframe
  slot
</template>

**Comment by zouyaoji** [comment]
hi @liyihongcug，非常感谢您的反馈，但是由于您没有使用 [创建 issue](https://zouyaoji.top/vue-cesium/#/zh/issues) 页面提交， 将直接被关闭， 谢谢！Thank you very much for your feedback,But since you did not submit it using the [create issue](https://zouyaoji.top/vue-cesium/#/en/issues) page, it will be closed directly, thank you!

**Comment by zouyaoji** [comment]
pug
